### ISSUE TITLE
Wildcard syntactic sugar for multi-column projection lists

### ISSUE THREAD

**Issue by mikedarcy** [informatics-isi-edu/ermrest#1]
Allow a '\*' or 'alias:\*' in projection lists to automatically expand to all columns in the current path entity context or all columns in the specified table instance, respectively.

**Comment by karlcz** [comment]
Mike, you can checkout the wildcard branch to experiment with this and Rob will hopefully review and merge #3 before too long.

**Comment by mikedarcy** [comment]
I have performed some initial tests on this and encountered an issue when combining a @sort clause with a wildcarded query. Take for example the following query where all tables contain relation PATNO:

https://localhost/ermrest/catalog/1/attribute/P:=PATIENT/V:=VITAL/$P/H:=BLCHEMHEMA/P:\*,H:\*,V:\*@sort(PATNO)?limit=2

This query returns:

400 Bad Request
The request is malformed. Sort key "PATNO" not among output columns.

This makes sense because all output columns have been aliased.  However trying to repsec the query with an alias on the argument to sort (e.g., @sort(P:PATNO)) results in:

400 Bad Request
The request is malformed. URL parse error at token: LexToken(:,':',1,84)

Not sure if this should be filed as a separate issue or not, but I will do so if you prefer.

**Comment by karlcz** [comment]
Oh, this actually makes sense.  Sort uses the OUTPUT column names and doesn't support qualified name syntax like `:`.  Can you re-test with the url-escaped `:` like `@sort(P%3APATNO)` and see if that works?

**Comment by mikedarcy** [comment]
Confirmed that this does work and that any previously aliased value can be used provided that it is properly escaped.  Not sure if the docs already state where explicit escaping is needed but if not this might be good to have in a reference table or some such.

**Comment by karlcz** [comment]
I added a little blurb to the docs to highlight this scenario about quoting.  Is this code still working for you?  Can we get the PR merged soon?

**Comment by karlcz** [comment]
This was merged to master.
