### ISSUE TITLE
Annotations at catalog level

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#101]
Periodically we encounter use cases where annotations over an entire catalog might be useful, rather than stopping at the named schema level. To support this, we'd need a few changes:
- [x] A change to per-catalog `_ermrest` schema to store such annotations
- [x] A new REST API such as `/catalog/1/annotation/` to manage them outside the usual `/catalog/1/schema/` hierarchy
- [x] A change to the `/catalog/1/schema` representation to include top-level annotations outside the named schema objects.

This seems like a relatively small implementation effort. The slight complication for existing deployments would be a change to existing catalogs to upgrade their schema. The existing split-role WSGI configuration will already route this new API to the `ermrestddl` daemon by default, since only specifically enumerated data-access APIs are routed to the `ermrest` daemon.

**Comment by karlcz** [comment]
I think I'll include this in the acls-eveywhere feature branch, since a similar change is happening to put catalog-wide acls under `/catalog/1/acl` but also include them in the `/catalog/1/schema` representation.

**Comment by karlcz** [comment]
This is done in acls-everywhere branch.  It has tests in the new test suite just like the other levels of model annotation.  A quick manual test for the upgrade process would be:

1. start with an existing test deployment from master
2. checkout the acls-everywhere branch
3. `make install` (as root)
4. `make deploy` (as root)
5. `curl ...  https://yourhost.domain.tld/ermrest/catalog/1/annotation` should return an empty object `{}` if you just upgraded an existing catalog 1 that previously lacked this feature
6. `curl ... https://yourhost.domain.tld/ermrest/catalog/1/schema` should include an empty `annotations: {}` field on the top-level object in the response document, i.e. annotations outside any particular schema.

**Comment by robes** [comment]
@karlcz Seems we have a boog..

```
$ curl https://dev.isrd.isi.edu/ermrest/catalog/1/annotation
409 Conflict
The request conflicts with the state of the server. relation "_ermrest.meta" does not exist
LINE 2: SELECT key, array_agg(value) AS values FROM _ermrest.meta
```

**Comment by robes** [comment]
@karlcz Just needed a restart of the service. So step 4.5 might need to be restart the service.

**Comment by karlcz** [comment]
did you run the acls-everwhere branch on that server?

during ermrest-deploy, it migrates the old meta table policy into the
new acl structure and nukes the old meta table.  it's a one-way trip.

you'd have to restore your meta table by hand or from a DB dump if you
want to go back from acls-everywhere to master right now.
