### ISSUE TITLE
Support the "download" query parameter

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/ermrest#104]
Currently, when you click the link to export the results in a CSV format, the browser is suggesting for the file name, the last part from the query path. This is a little bit confusing, as it contains elements from the `ermrest` filter (for example `$A@sort(id)`).
The suggestion is to include in the query the `download` parameter with the file name to be used by the browser.
The `ermrest` will include it in the response header.

**Comment by karlcz** [comment]
I think what you want is to control a response header like:

`Content-Disposition: attachment; filename="your filename.csv"`  or 
`Content-Disposition: attachment; filename*=UTF-8''your%20filename.csv`

Right? (This is what I find in RFC 6266... which we already use in hatrac I think)

**Comment by svoinea** [comment]
Yes. That is what I want.

**Comment by karlcz** [comment]
This is in ermrest/master in commit c1a3c1f87538715aae3e50c0e79d493a59783838

**Comment by mikedarcy** [comment]
Works for me in Chaise with this commit: https://github.com/informatics-isi-edu/chaise/commit/5cc9cf84e565725ce585f5b674281fe8c0defcee
