### ISSUE TITLE
Attribute Group API Put fails when column names are aliased

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrest#108]
When a Put request is made to the `attributegroup` API, it returns a 409 Conflict error:
`Error 409 Conflict The request conflicts with the state of the server. Input row key ((None,)) does not match existing entity.`

It appears that when an alias is used in the URI, ermrest is not able to find a column using that alias.

**Comment by karlcz** [comment]
Fix pushed to master. Please confirm once the hourly update deploys...

**Comment by karlcz** [comment]
@jrchudy please close this once you verify that it is working still on dev.isrd.  i've verfified that the latest code is installed by the hourly update...

**Comment by jrchudy** [comment]
I verified that this is still working today after making a few requests to the server.  I tested updating an entity's non-key columns in one request, key columns in another, and a combination of columns in another.
