### ISSUE TITLE
Postgres errors returned to user in certain error contexts

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrest#110]
I am being presented with Postgres errors when certain 409 errors occur. The most recent error is the following:
```
{ [Error: 409 Conflict
The request conflicts with the state of the server. could not serialize access due to concurrent update

]
  code: 409,
  status: undefined,
  message: '409 Conflict\nThe request conflicts with the state of the server. could not serialize access due to concurrent update\n\n' }
```

Edit: removed an error that was a client mistake (deleted a table before trying to use it).

**Comment by jrchudy** [comment]
As @karlcz mentioned at lunch, the above errors are actually ermrest error messages and not the postgres one that I had discovered when testing reference.update yesterday.

I am not able to reproduce that error anymore.

**Comment by karlcz** [comment]
Looking at the dev server logs I saw two classes of postgres errors that can happen under concurrent access.  I just pushed changes to map these to a 503 Service Unavailable HTTP error so the client can retry the request.

I'm not sure if you'll encounter these errors again since the underlying trigger was your new test suite executing things concurrently when you thought they were serialized...

**Comment by karlcz** [comment]
@jrchudy  if you can reproduce the concurrent failure (by running a *broken* test suite again?) it would be interesting to confirm that we get 503 responses instead of 409.

**Comment by jrchudy** [comment]
I can confirm that when trying to run 2 updates at the same time I receive this message:
```
{ [Error: 503 Service Unavailable
The service is temporarily unavailable: Transaction aborted..
]
  code: 503,
  status: undefined,
  message: '503 Service Unavailable\nThe service is temporarily unavailable: Transaction aborted..\n' }
```

Upon looking at /var/log/messages.txt, I can verify that there is the following error:
`Postgres error: ERROR:  could not serialize access due to concurrent update#012 (40001)`
followed by the `503 Service Unavailable` error.
