### ISSUE TITLE
400 error when assigning null value to annotation

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/ermrest#111]
I modified a dummy schema in ermrestjs tests to add the `2016:generated` and `2016:immutable` annotations to 2 columns, like so:
```
                {
                    "name": "table_1_generated",
                    "type": { "typename": "text" },
                    "annotations": {
                        "tag:isrd.isi.edu,2016:generated": null
                    }
                },
                {
                    "name": "table_1_immutable",
                    "type": { "typename": "text" },
                    "annotations": {
                        "tag:isrd.isi.edu,2016:immutable": null
                    }
                }
```
... which led to the following error while running ermrestjs tests:

```
{ data: '400 Bad Request\nThe request is malformed. Null value is not a valid annotation.\n',
  statusCode: 400 }
```

If I change the annotations' payloads to `{}` (empty object), the error disappears and the schema is created normally. However, given that both the `immutable` and `generated` sections in the annotations guide says there is no content for each of these annotations, I would've expected `null` to be an acceptable value.

**Comment by hongsudt** [comment]
If the specification allows the value to be null or empty, then please go
ahead and fix this problem.

**Comment by hongsudt** [comment]
@karlcz can you confirm @howdyjessie 's question? I see no reason not to support null value.

**Comment by karlcz** [comment]
I pushed a fix for this to master...  seems like an explicit test was rejecting null for no real reason and has been lurking in that code since it was first added over a year ago...

**Comment by howdyjessie** [comment]
Looks like it's fixed! Tested this with null values and now I don't get the error anymore.
