### ISSUE TITLE
Error msg when trying to create a new catalog

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/ermrest#113]
While trying to create a new catalog on gpcr-dev I get the following error:
Wed Oct 19 11:21:58.529573 2016] [:error] [pid 25883] [remote 128.9.132.104:248] mod_wsgi (pid=25883): Exception occurred processing WSGI script '/usr/lib/python2.7/site-packages/ermrest/ermrest.wsgi'.
[Wed Oct 19 11:21:58.529652 2016] [:error] [pid 25883] [remote 128.9.132.104:248] Traceback (most recent call last):
[Wed Oct 19 11:21:58.529674 2016] [:error] [pid 25883] [remote 128.9.132.104:248]   File "/usr/lib/python2.7/site-packages/web/application.py", line 281, in wsgi
[Wed Oct 19 11:21:58.529893 2016] [:error] [pid 25883] [remote 128.9.132.104:248]     result = peep(result)
[Wed Oct 19 11:21:58.529924 2016] [:error] [pid 25883] [remote 128.9.132.104:248]   File "/usr/lib/python2.7/site-packages/web/application.py", line 261, in peep
[Wed Oct 19 11:21:58.529947 2016] [:error] [pid 25883] [remote 128.9.132.104:248]     firstchunk = iterator.next()
[Wed Oct 19 11:21:58.529960 2016] [:error] [pid 25883] [remote 128.9.132.104:248]   File "/usr/lib/python2.7/site-packages/web/application.py", line 647, in wrap
[Wed Oct 19 11:21:58.529975 2016] [:error] [pid 25883] [remote 128.9.132.104:248]     yield next()
[Wed Oct 19 11:21:58.529984 2016] [:error] [pid 25883] [remote 128.9.132.104:248]   File "/usr/lib/python2.7/site-packages/web/application.py", line 639, in next
[Wed Oct 19 11:21:58.529998 2016] [:error] [pid 25883] [remote 128.9.132.104:248]     return result.next()
[Wed Oct 19 11:21:58.530007 2016] [:error] [pid 25883] [remote 128.9.132.104:248]   File "/usr/lib/python2.7/site-packages/ermrest/apicore.py", line 296, in wrapper
[Wed Oct 19 11:21:58.530024 2016] [:error] [pid 25883] [remote 128.9.132.104:248]     if e.pgcode[0:2] == '08':
[Wed Oct 19 11:21:58.530054 2016] [:error] [pid 25883] [remote 128.9.132.104:248] TypeError: 'NoneType' object has no attribute '**getitem**'

**Comment by karlcz** [comment]
I think this bug was already addressed in 54644511
