### ISSUE TITLE
number format pattern

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#115]
We need to start working on the template. I hear quite a few complaints about the GUI presenting an ID column in a number format (e.g. with , separating thousands). 

@karlcz @robes is there any js number formatting template that we can use?

**Comment by karlcz** [comment]
Isn't this what the column-display pre_format field is for?

**Comment by robes** [comment]
@hongsudt not sure what you mean by js number formatting template.

Sounds like if the concern is not formatting the number when it is a ID column, maybe we either need a heuristic for that, or we need a turn off formatting annotation?

**Comment by karlcz** [comment]
I think this issue is mostly an ermrestjs issue?  We need to pick a posix-style formatting library so we can implement the pre_format display annotation. Then we can update the annotations doc with more precise dialect info for the format directives.

**Comment by hongsudt** [comment]
Issue moved to [informatics-isi-edu/ermrestjs #299](https://github.com/informatics-isi-edu/ermrestjs/issues/299) via [**ZenHub**](https://www.zenhub.com/)
