### ISSUE TITLE
Don't add extra % to column names that have %s in them

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/ermrest#119]
ERMrest may be adding an extra `%` to column names when dealing with names that have %s in them.

This problem can be seen when attempting to add/edit a row on dev.isrd.isi.edu, catalog 1, `public` schema, `form_test` table, where a column `c%_text` exists.

**Comment by karlcz** [comment]
I've pushed a fix and updated test cases to master. Please confirm when it works for you on the dev server and close this after...

**Comment by howdyjessie** [comment]
Thanks, this works fine now.
