### ISSUE TITLE
Makefile depends on svn

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrest#12]
Just caught this little easter egg.

https://github.com/informatics-isi-edu/ermrest/blob/602a386ba5bedce8c88963e3c268c68c9574ca5b/Makefile#L1

I'm sure there's a git equivalent.

**Comment by karlcz** [comment]
This variable isn't even used in the Makefile so I'll just remove it.  Done in 3520778e5d75909bf7671762db4ab07c8319891d in refactor2015 branch...
