### ISSUE TITLE
Key Annotation

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrest#127]
After addition of Key pseudo-column, we need customization for its attributes. These customization can be done via annotation and include:
- column order: The same way we define `column_order` on [foreign key](https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2016-foreign-key) and [column](https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2016-column-display).
- Displayname: Equivalent of `to_name` for foreign keys.
- Value presentation: It could be the same as `markdown_pattern`.

**Comment by karlcz** [comment]
This is pushed to ermrest/master as two enhancements:

1. allow 2015:display annotation on keys to customize naming
2. add 2017:key-display annotation to customize column order or apply markdown patterns
