### ISSUE TITLE
Key and foreign key annotations bug

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrest#129]
When I try to create a `Table` that has `annotations` in its `keys` attribute, it doesn't store the annotations.
Sample request:
- Request URL: https://dev.isrd.isi.edu:443/ermrest/catalog/16913/schema/reference_schema/table
- Payload:
```json
{
    "comment": "comment",
    "kind": "table",
    "table_name": "reference_table_outbound_fks",
    "schema_name": "reference_schema",
    "keys": [ {
        "unique_columns": ["col_1", "id"],
        "names": [
            ["reference_schema", "ref_table_key"]
        ],
        "annotations": {
            "tag:misd.isi.edu,2015:display": {
                "name": "key"
            },
            "tag:isrd.isi.edu,2017:key-display": {
                "*": {
                    "markdown_pattern": "{{col_1}}"
                }
            }
        }
    }],
    "foreign_keys": [],
    "column_definitions": [{
        "name": "id",
        "nullok": false,
        "type": {
            "typename": "text"
        },
        "comment": ""
    }, {
        "name": "col_1",
        "default": null,
        "type": {
            "typename": "text"
        },
        "comment": ""
    }],
    "annotations": {}
}
```

In fact the `annotations` is missing on every level of retrieval (schema, table, and key), and also it hasn't been stored in the database. After discussing it with @karlcz, we think that it failed to insert the annotations into the database.

**Comment by karlcz** [comment]
This should be fixed in the latest master at revision 487916b94313c3dc154b95c83c9abab826c20b7b.

Through added test cases, I found this affected both key and foreignkey annotations when bundled as a sub-document rather than creating them via the most narrowly scoped `.../annotation/` API on an existing key or foreign key.
