### ISSUE TITLE
Internal server error on CSV upload

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/ermrest#13]
<pre>
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248] 'got exception "\\'ascii\\' codec can\\'t decode byte 0xe2 in position 127: ordinal not in range(128)"'
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248] ['Traceback (most recent call last):\\n',
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]  '  File "/usr/lib/python2.6/site-packages/ermrest/ermrest_apis.py", line 250, in METHOD\\n    first = result.next()\\n',
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]  '  File "/usr/lib/python2.6/site-packages/ermrest/sanepg2.py", line 146, in pooled_perform\\n    result = bodyfunc(conn, cur)\\n',
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]  '  File "/usr/lib/python2.6/site-packages/ermrest/url/ast/data/path.py", line 197, in wrapbody\\n    raise rest.BadRequest(e.message)\\n',
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]  '  File "/usr/lib/python2.6/site-packages/ermrest/exception/rest.py", line 39, in __init__\\n    WebException.__init__(self, status, headers=headers, data=data, desc=desc)\\n',
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]  '  File "/usr/lib/python2.6/site-packages/ermrest/exception/rest.py", line 29, in __init__\\n    self.detail = urlquote(desc % data)\\n',
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]  "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 127: ordinal not in range(128)\\n"]
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248] Traceback (most recent call last):
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]   File "/usr/lib/python2.6/site-packages/web/application.py", line 239, in process
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]     return self.handle()
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]   File "/usr/lib/python2.6/site-packages/web/application.py", line 230, in handle
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]     return self._delegate(fn, self.fvars, args)
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]   File "/usr/lib/python2.6/site-packages/web/application.py", line 405, in _delegate
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]     return handle_class(f)
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]   File "/usr/lib/python2.6/site-packages/web/application.py", line 396, in handle_class
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]     return tocall(*args)
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]   File "/usr/lib/python2.6/site-packages/ermrest/ermrest_apis.py", line 286, in PUT
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]     return self.METHOD('PUT')
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]   File "/usr/lib/python2.6/site-packages/ermrest/ermrest_apis.py", line 250, in METHOD
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]     first = result.next()
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]   File "/usr/lib/python2.6/site-packages/ermrest/sanepg2.py", line 146, in pooled_perform
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]     result = bodyfunc(conn, cur)
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]   File "/usr/lib/python2.6/site-packages/ermrest/url/ast/data/path.py", line 197, in wrapbody
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]     raise rest.BadRequest(e.message)
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]   File "/usr/lib/python2.6/site-packages/ermrest/exception/rest.py", line 39, in __init__
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]     WebException.__init__(self, status, headers=headers, data=data, desc=desc)
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]   File "/usr/lib/python2.6/site-packages/ermrest/exception/rest.py", line 29, in __init__
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]     self.detail = urlquote(desc % data)
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 127: ordinal not in range(128)
[Thu Jul 23 15:06:01 2015] [error] [client 128.9.132.248]
</pre>

**Comment by karlcz** [comment]
We did a bit of triage and it looks like the data file was causing an integrity error in Postgres which is coming back with an error detail string that is UTF-8 encoded with unicode characters coming from the input data and choking while trying to embed this error string into the ERMrest rest exception response.

This [line in exception/rest.py](https://github.com/informatics-isi-edu/ermrest/blob/cfb27ed2ca9d53ec9dbb62634f7b502e0b747078/ermrest/exception/rest.py#L29) seems to be the place we need to deal with already encoded UTF8 data values to protect ourselves.

**Comment by karlcz** [comment]
I think this is fixed once #15 is merged..
