### ISSUE TITLE
Customizable pseudo columns

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#133]
Some use case discussions raised the question of whether something more subtle than the `*` wildcard column could be used for searches.  Right now, it supports text-based predicates, e.g.`::regexp::`, and evaluates as a disjunctive match across a text representation of *all* columns.

## Use Cases

1. Customize the current `*` behavior, namely to allow pruning of the list of columns included in this search mode.
2. Introduce new search modes which can have even more customized lists of columns appropriate for certain application contexts, and a different API encoding to select which search mode is desired.
3. It should be possible to mix the modes in one query, e.g. different modes used as different predicates on different table instances in one joined query.

## Approaches

Depending on how much generality we seek, there are two proposed approaches. The first introduces just a small number of new, fixed search terms to complement the existing `*` column. The second introduces a much more general extension point where new search terms can be managed dynamically.

### Add new fixed syntax terms

Enable a `**` pseudo column and some ability to customize the column lists backing both `*` and `**` with automatic default behaviors if unconfigured.

This would be the smallest hack for the codebase and API, but leaves no real option to discover whether the facility is available on a given server nor to introduce more application-specific syntax. We'd have to just roll out the new server first and then roll out clients capable of using the feature. Older servers would return an error for the unknown pseudo column.

### Add arbitrary extension mechanism

(This section edited 2017-02-15 based on offline discussions.)

Introduce a psuedocolumn resource which can define a named, custom search pseudo column on a table. The client can discover the available search columns and annotations could guide their use, e.g. for specific application contexts. This would be a new sub-resource under tables, allowing for discovery of server capabilities.

The `*` column could be automatically configured for backwards compatibility. Others could be added (including the `**` column if we combine this with previous approach).

There should be some sort of *column kind* property on the pseudo column resources for further extensibility. These initial ones would be a *search* or *filter* kind, i.e. they are subject to search predicates  but cannot be projected as outputs. Others could potentially have different capabilities in the future.

@hongsudt @robes

**Comment by karlcz** [comment]
Updated description to suggest pseudocolumn sub-resource...

**Comment by karlcz** [comment]
This feature could be useful in the acls-everywhere branch to also advertise a dynamic rights psuedo column when one is available to report row-specific access privileges for the client.

**Comment by robes** [comment]
Comment on the original description: it doesn't explicitly indicate that the columns could included in the pseudo-column could be anything other than columns of the same table. I thought one of the use cases for this was the "deep search" use case where we want the search to hit the columns of entities referenced by a FK of the current table.

**Comment by karlcz** [comment]
Closing this issue because I think it was superseded by changes in Chaise to customize search behavior. Some projects continue to explore other forms of ETL/computed search indexes, but we haven't so far identified a generic/configurable ermrest extension that would really address these project-specific goals.
