### ISSUE TITLE
POST .../foreignkey appears to be broken

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrest#136]
I got errors trying to POST a foreign key and noticed this in model/key.py:

```
INSERT INTO _ermrest.model_pseudo_keyref                                                                                                                                          
  (from_schema_name, from_table_name, from_column_names, to_schema_name, to_table_name, to_column_names, comment, name)                                                           
  VALUES (%s, %s, ARRAY[%s], %s, %s, ARRAY[%s], %s)                                                                                                                               
  RETURNING id                                                                                                                                                                    
```

By my count, that's eight insert columns and seven value columns.

(This is a really low priority for me. I do this stuff directly through sql, and was just using the REST api to debug a problem in one of my scripts).

**Comment by karlcz** [comment]
Can you test the small fix I pushed to master?  This isn't something we can test in our regression suite right now, because we don't have any support for creating views via the REST API, which means there is no way to cause these psuedo keyref scenarios via the http-only test client...

**Comment by karlcz** [comment]
I set up a manual test environment and confirmed that this works for all combinations
- view references table
- view references view
- table references view
