### ISSUE TITLE
Document command line tools

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrest#138]
As far as I can tell none of ermrest's command line utilities is documented except for `ermrest-registry-purge`. We need comparable levels of docs for all of these.

- already covered by install guide and has no meaningful end-user options
    - ermrest-deploy
- DB maintenance helpers for system integrators/operators (should think about making them more uniform in flavor?)
    - ermrest-freetext-indices: for legacy users who manipulate DB schema outside ermrest
    - ermrest-registry-purge
- previous scripts which no longer exist in master
    - ermrest-db-work
    - ermrest-registry-deploy
    - ermrest-registry-purge
    - ermrest-valuemap-recreate
    - ermrest-valuemap-work
    - ermrest-undeploy (not really maintained, should just delete)

**Comment by karlcz** [comment]
I edited the issue description to categorize the topics and give some extra notes to help prioritize any documentation effort...

**Comment by karlcz** [comment]
Any work on this documentation should be contributed to the stateful-model branch or deferred until after the corresponding PR #165 is merged, since that branch dropped most of the obsolete scripts listed above...

**Comment by karlcz** [comment]
I finally added a little user-doc about the legacy ermrest-freetext-indices script.
