### ISSUE TITLE
Incorrect error number

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/ermrest#139]
On dev.isrd.isi.edu, when I make this PUT request on the attributegroup API with a long composite key: `https://dev.isrd.isi.edu/ermrest/catalog/19255/attributegroup/multi-column-types:table_1/id_o:=id,int2_null_col_o:=int2_null_col,int2_col_o:=int2_col,int2_col_gen_o:=int2_col_gen,int4_null_col_o:=int4_null_col,int4_col_o:=int4_col,int4_col_gen_o:=int4_col_gen,int8_null_col_o:=int8_null_col,int8_col_o:=int8_col,int8_col_gen_o:=int8_col_gen,float4_null_col_o:=float4_null_col,float4_col_o:=float4_col,float4_col_gen_o:=float4_col_gen,float8_null_col_o:=float8_null_col,float8_col_o:=float8_col,float8_col_gen_o:=float8_col_gen,text_null_col_o:=text_null_col,text_col_o:=text_col,text_col_gen_o:=text_col_gen,longtext_null_col_o:=longtext_null_col,longtext_col_o:=longtext_col,longtext_col_gen_o:=longtext_col_gen,markdown_null_col_o:=markdown_null_col,markdown_col_o:=markdown_col,markdown_col_gen_o:=markdown_col_gen,bool_null_col_o:=bool_null_col,bool_true_col_o:=bool_true_col,bool_true_col_gen_o:=bool_true_col_gen,bool_false_col_o:=bool_false_col,bool_false_col_gen_o:=bool_false_col_gen,timestamp_null_col_o:=timestamp_null_col,timestamp_col_o:=timestamp_col,timestamp_col_gen_o:=timestamp_col_gen,timestamptz_null_col_o:=timestamptz_null_col,timestamptz_col_o:=timestamptz_col,timestamptz_col_gen_o:=timestamptz_col_gen,date_null_col_o:=date_null_col,date_col_o:=date_col,date_col_gen_o:=date_col_gen,fk_null_col_o:=fk_null_col,fk_col_o:=fk_col,fk_col_gen_o:=fk_col_gen;id_n:=id,int2_null_col_n:=int2_null_col,int2_col_n:=int2_col,int2_col_gen_n:=int2_col_gen,int4_null_col_n:=int4_null_col,int4_col_n:=int4_col,int4_col_gen_n:=int4_col_gen,int8_null_col_n:=int8_null_col,int8_col_n:=int8_col,int8_col_gen_n:=int8_col_gen,float4_null_col_n:=float4_null_col,float4_col_n:=float4_col,float4_col_gen_n:=float4_col_gen,float8_null_col_n:=float8_null_col,float8_col_n:=float8_col,float8_col_gen_n:=float8_col_gen,text_null_col_n:=text_null_col,text_col_n:=text_col,text_col_gen_n:=text_col_gen,longtext_null_col_n:=longtext_null_col,longtext_col_n:=longtext_col,longtext_col_gen_n:=longtext_col_gen,markdown_null_col_n:=markdown_null_col,markdown_col_n:=markdown_col,markdown_col_gen_n:=markdown_col_gen,bool_null_col_n:=bool_null_col,bool_true_col_n:=bool_true_col,bool_true_col_gen_n:=bool_true_col_gen,bool_false_col_n:=bool_false_col,bool_false_col_gen_n:=bool_false_col_gen,timestamp_null_col_n:=timestamp_null_col,timestamp_col_n:=timestamp_col,timestamp_col_gen_n:=timestamp_col_gen,timestamptz_null_col_n:=timestamptz_null_col,timestamptz_col_n:=timestamptz_col,timestamptz_col_gen_n:=timestamptz_col_gen,date_null_col_n:=date_null_col,date_col_n:=date_col,date_col_gen_n:=date_col_gen,fk_null_col_n:=fk_null_col,fk_col_n:=fk_col,fk_col_gen_n:=fk_col_gen?cid=recordedit`,

I receive the following response from ERMrest:
`503 Service Unavailable
The service is temporarily unavailable: cannot use more than 32 columns in an index
.`, which should be a 4xx-class error instead.

**Update:** The key set in this request url is so long because ermrestjs currently constructs the key set for PUTs based on a table's visible columns instead of a primary key/shortest key. This is because we wanted to avoid using ETag matching in PUTs.

**Comment by karlcz** [comment]
This is fixed in two parts in master...

1. map this kind of error to 400 BadRequest instead of 503, since it represents an implementation limit where a retry will not help
2. change ermrest to avoid making overly long indices on the temporary input table used in the attributegroup API

**Comment by howdyjessie** [comment]
Seems to work. Repeating the same PUT request with the long key as described in the issue description produces a 200 now instead of the 503 error.
