### ISSUE TITLE
Proposed improvements to 'DELETE /catalog/N'

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#14]
The DELETE /catalog/N interface responds 200 OK but does not change the state of the server. The catalog is still in the registry and visible to clients and this delete request can be issued repeatedly.

We should:
1. Add a 'deleted' flag to the registry and/or the catalog itself that causes it to respond with NotFound on subsequent access.
2. Add some maintenance script to periodically process deleted catalogs, e.g. to handle asynchronous shutdown and purge.  We should hasten the closure of connection pools to that database and eventually rename, archive, and/or delete the database, perhaps depending on a policy setting in ermrest_config.json.

**Comment by robes** [comment]
Okay. So there is a bug in the delete. Appears to be some kind of a regression. The delete definitely did work. This can be fixed trivially and it restores the original functionality which was to delete the catalog (id, descriptor) row from the simple registry database while leaving the catalog db in tact.

Sidenote: the interface responds with 204 No Content actually.

**Comment by robes** [comment]
How much provenance do we want to produce in this feature? For example, we could:
- simply have a `deleted` flag that indicates the catalog has been deleted and should not be served to clients anymore;
- have a `deleted on` timestamp (alone or in addition to the `deleted` flag); this would allow the user to develop better purge policies, like `purge all catalogs that were deleted over 1 month or 1 year ago`;
- we could then have a `purged` flag and/or `purged on` timestamp so that the registry maintains a tombstone of the catalog effectively;
- which leads to the final point, should the registry (I mean the `catalog/` and `catalog/N` resources) always return something (per ACL policies) so that the service always at least responds with the tombstone of the catalog.

**Comment by karlcz** [comment]
The REST API should return 404 Not Found once the DELETE command
succeeded.  To do otherwise would violate HTTP client expectations.

I think the tombstone is useful until the real DB is purged.  This
will be for the use of local admin tools/cleanup scripts that can
inspect the registry outside of the ERMrest API.  Once it has purged,
I see no reason to keep entries in the registry DB versus just a log
file somewhere that can be archived if desired.

**Comment by robes** [comment]
Good point about the REST semantics. Re: those local admin tools... looks like we need that `ermrest-registry-manage` script back in the repo don't we? ;-)

**Comment by karlcz** [comment]
Perhaps, but not in its previous form.  I expect some single-task
scripts that call psql, pgdump, and/or dropdb directly.

**Comment by robes** [comment]
Another thought here. The `simple_registry` table definition is going to change. I would rather not have ERMrest service logic doing `ALTER TABLE` statements. I really prefer to have a `update-XYZ.sql` script that the system admin runs on their `ermrest` database to migrate an existing database to the new schema. This is different than I think we have been doing it so far. We don't really have a subdir for this in the repo. Maybe its time we start doing this and having a subdir for these types of migration scripts.

**Comment by karlcz** [comment]
To date, we've just changed the behavior for new deploys/new catalogs
and documented (often just in the commit logs) how someone could
upgrade a database in-place, leaving it to the admin to make schema
changes idempotently.

To make friendlier, fool-proof upgrade scripts, you probably need to
add some logical version number to the schema too, so the script
can check whether it needs to be applied.

**Comment by robes** [comment]
Required update to your ermrest db:

```sql
ALTER TABLE ermrest.simple_registry
ADD COLUMN deletedon timestamp with time zone DEFAULT NULL;
CREATE INDEX ON ermrest.simple_registry (deletedon);
CREATE INDEX ON ermrest.simple_registry (id, deletedon);
```
