### ISSUE TITLE
Data version tracking is incomplete and does not cover views

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#145]
ERMrest has some primitive support for exposing SQL views as read-only entity sets. However, the built-in data-version tracking for HTTP ETags does not understand views and their data dependencies. So, an ERMrest query URL may respond with stale ETags or return `304 Not Modified` to a stale `If-None-Match` request header (i.e. for browser cache maangement) for a query involving a view.

We already have some ugly hacks to deal with data-dependencies between tables due to foreign keys. We should probably consider an alternative approach which can handle multiple scenarios, and drop that ad hoc code.

1. Produce a transitive-closure of data dependencies between table-like objects. This can be done from `pg_catalog` queries if we adapt what `psql` is capable of telling us about a table or view.
2. During `data_change_event()` for a table, determine an upper bound set of affected tables based on the preceding query, and update version entries for all of them.

If necessary for performance, we could cache the results of the transitive-closure query and reuse them. We'd need to refresh the cache on every `model_change_event()`.  This might be a good use case for a materialized view...

To date, SQL views in ERMrest have only been reliable in read-only catalogs, i.e. where any externally-loaded data is followed by `model_change_event()` which trumps any table-level version tracking.  But as we get more catalogs with incremental update by REST API and more use of SQL views for dashboards and other presentation, problems with stale caching are going to emerge...

@hongsudt @robes @carlkesselman

**Comment by karlcz** [comment]
BTW, some have asked about workarounds for this problem.  For less impact than brute-force `_ermrest.model_change_event()` calls, you can execute `_ermrest.data_change_event(schema_name, view_name)` to announce changes, i.e. using an `after insert, update, delete` trigger on each data source consumed by the view.

**Comment by karlcz** [comment]
I'm thinking of just using a brute-force approach of considering latest table version across all tables to determine the version for a view, i.e. assume worst case that all tables may contribute to the view result.  This will cause more cache misses but is safe.

**Comment by karlcz** [comment]
The latest code in the stateful-model branch considers all table versions to determine the latest version of a view, as discussed in the previous comment.

**Comment by robes** [comment]
I can't tell if the `stateful-model` branch is merged. I see it indicates tests are passing and its 45 commits ahead of master. Is this something you need a volunteer for testing?

**Comment by karlcz** [comment]
It has not been made into a PR yet, but yes it could use friendly
testing.

I'm still working through my first real end-to-end pilot test of the
branch, i.e. with realistic catalog content instead of the test suite.

**Comment by robes** [comment]
Would it help if we use this branch on the fb dev server? We use a 'alternate-table' view in one place.
