### ISSUE TITLE
Add and enforce system-managed columns

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#158]
## Overview

To improve scientific data management, we plan to add five standard columns to all tables in ERMrest. These system-managed columns will have fixed and predictable naming, types, and behavior. Since they will appear in many data and query serializations, we chose short abbreviations for each column name:

| Name | Type | Purpose |
|---|---|---|
| RID | ermrest_rid | a unique not-null identifier for each row in a table |
| RCT | ermrest_rct (domain over timestamptz) | not-null row creation time |
| RMT | ermrest_rmt (domain over timestamptz) | not-null latest row modification time |
| RCB | ermrest_rcb (domain over text) | row created by (client primary ID guid) |
| RMB | ermrest_rmb (domain over text) | latest row modified by (client primary ID guid) |

## Interface Guarantees

Once this mechanism is in place and enforced, a client should be able to rely on the following behaviors from a compliant ERMrest catalog:

1. The five columns *must* appear in each mutable table and *must* have the column types described above.
2. Every row *must* have a unique RID value assigned at creation time and this value *must not* be recycled for use by another row in the same table.
3. Every row *must* have an immutable RCT time set during row creation.
4. Every tuple *must* have an RMT set during tuple creation. The RMT value *must* be equal to or greater than the RCT and every previously visible RMT for the same RID in the same table.
5. The RCB and RMB values *must* be comparable to the client ID space exposed by webauthn as the `id` field of the object returned from `GET /authn/session`. A NULL value may be present to indicate unknown provenance, e.g. for rows manipulated by server-side logic. However, a DBA may also substitute a distinct client ID representing an administrator or *robot* identity in such cases.
6. These system-managed columns have enforced policies described below.
   - The RID, RCT, and RMT are visible to all clients who can view a row
   - The RCB and RMB may be hidden from some clients who can view other row content
   - Clients may not supply substitute/override values for any of these columns

| Column | Forced Column ACLs | Default Column ACLs |
|---|---|---|
| RID | `{"select": ["*"], "update": [], "insert": []}` | n/a |
| RCT | `{"select": ["*"], "update": [], "insert": []}` | n/a |
| RMT | `{"select": ["*"], "update": [], "insert": []}` | n/a |
| RCB | `{"enumerate": ["*"], "update": [], "insert": []}` | `{"select": ["*"]}` |
| RMB | `{"enumerate": ["*"], "update": [], "insert": []}` | `{"select": ["*"]}` |

## Implementation Techniques

1. Initially, we will define `ermrest_rid` as a domain over int8 and generate values from a catalog-wide non-cycling sequence which is limited to approximately 2^43 to be represented safely as an integer in Javascript.
   - We could change this to other types in the future, e.g. a textual representation of a larger int, a UUID, etc.
2. We will define RCT and RMT to default to `now()` which is transaction start time.
3. We will define RCB and RMB to default to `_ermrest.current_client()`.
4. ERMrest will use SQL constructs that always set a default for these columns.
5. We may want a trigger to further automate and enforce the column rules even if someone runs SQL that bypasses ermrest.

## Transition Planning

This feature set could roll out in phases for a smoother transition.

1. Existing state, no standard columns
2. Roll out new definitions in ERMrest
   - SQL domains
   - sequence to use with RID
   - trigger function to manage columns
   - revised sample ermrest_config.json w/ new domains
3. Upgrade existing catalog models via an offline tool
   - generate DDL to add columns to all tables
   - generate DDL to add trigger to all tables
   - add annotations to declare new columns as immutable and generated
   - add appropriate static ACLs on new columns
   - consider custom scenarios where existing columns should be repurposed as RCT, RMT, RCB, RMB
4. Roll out new table structures ERMrest
   - add columns on all tables created by rest apis
   - add appropriate ACL management restrictions
5. Start flagging non-standard tables
   - extend "primary key" enforcement logic to check for standard columns
6. Disable option to skip "primary key" enforcement
7. Consider new features which depend on standard columns...

## Other Decisions to Make

- How does table creation API handle presence of the 5 new columns?
- How does ermrest-deploy handle legacy catalogs which aren't compliant?
- How does ermrest handle legacy catalogs which aren't compliant?

**Comment by karlcz** [comment]
These columns are implemented in the stateful-model branch.  They have special authz logic to prevent client writes, while still allowing normal ACL mechanisms to control read access.

The schema API requires that system columns be explicitly configured in each new table definition. Introspection likewise requires that tables already conform. There is no automatic upgrade to add system columns as part of software update, since this is a potentially invasive task best left to a DBA.

The data APIs have a few convenience features for system columns
1. The columns are automatically included in the `?defaults` parameter implicitly, to allow naive entity POST requests to keep working
2. The columns are automatically excluded as update targets in entity PUT requests.

This is prototype code and needs further review and testing.

**Comment by robes** [comment]
Any qualms with using a table's `RCB` column in a dynamic ACL binding?

**Comment by karlcz** [comment]
That should work.
