### ISSUE TITLE
Cannot page by aggregate function result

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrest#162]
Ermrest doesn't know that `cnt()` produces integer results, and instead uses the column type.

Example:
https://dev.isrd.isi.edu/ermrest/catalog/1/attributegroup/isa:dataset/value:=accession;count:=cnt(*)@sort(count::desc::,value)@after(1,FB00000123.01)

**Comment by karlcz** [comment]
A fix for this is pushed to master.  It allows paging by results of `cnt`, `cnt_d`, and `array` aggregate funcs. The `array` support doesn't seem very useful to me, but I decided to fix it consistently while digging around in that part of the codebase...  it uses the `jsonb` value ordering in PostgreSQL while the other two use the `int8` type and ordering.

**Comment by RFSH** [comment]
Thanks for the fix. Works as expected.
