### ISSUE TITLE
Bad SQL for wildcard search when columns are not enumerable

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrest#163]
I got this error from https://dev.rebuildingakidney.org/~ashafaei/chaise/recordset/#2/Antibody:Antibodies:
```
409 Conflict
The request conflicts with the state of the server. column t0.Provenance does not exist
LINE 8: ...alog_Number") ~* 'abc'::text) OR (_ermrest.astext(t0."Proven...
```
(filing it here because Karl says ermrest should have given it a higher-level error).

https://dev.rebuildingakidney.org/ermrest/catalog/2/schema/Antibody/table/Antibody_Media_Files/column/Provenance/acl returns

```
{
  "enumerate": []
}
```

**Comment by ljpearlman** [comment]
Actuallly, how was I able to make that REST call at all? Since no one (including me) has enumerate rights, shouldn't that have failed?

**Comment by karlcz** [comment]
I need more info than this.  What was the actual REST query URL that had this error?  Can you give the original request URL?  It would also help to turn on SQL logging on the server and capture the whole SQL statement that raises this error.

I'm not sure which rest call you are referring to in your second question.  The catalog owner always has implicit rights to everything, even if ACLs are empty, so you'd be able to access that second ACL URL if you are an admin.  I get a 404 Not Found trying to access it as an anonymous user.

**Comment by karlcz** [comment]
OK, it seems like the error comes from the use of the `*` pseudo column for a wildcard search.  I can reproduce the error with curl:

    curl 'https://dev.rebuildingakidney.org/ermrest/catalog/2/entity/Antibody:Antibody_Media_Files/*::regexp::abc'

**Comment by karlcz** [comment]
A fix for this is pushed to master.

**Comment by karlcz** [comment]
@ljpearlman do you plan to confirm this fix in your own deployment?  if not, can you just close the issue?

I already confirmed it to my satisfaction in my own tests... and we can always reopen if a problem is encountered later.
