### ISSUE TITLE
Ermrest sometimes includes temporary schemas in its catalog.

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrest#168]
The rest call  https://dev.rebuildingakidney.org/ermrest/catalog/3/schema included this in the schema:
```
"schemas": {
    "pg_temp_8": {
      "comment": null,
      "tables": {},
      "rights": {
        "owner": true,
        "create": true
      },
      "acls": {},
      "schema_name": "pg_temp_8",
      "annotations": {}
    },
    "pg_toast_temp_8": {
      "comment": null,
      "tables": {},
      "rights": {
        "owner": true,
        "create": true
      },
      "acls": {},
      "schema_name": "pg_toast_temp_8",
      "annotations": {}
    },
```
These are apparently schemas used by postgres to contain temporary tables (created by ermrest?) and shouldn't be part of the catalog.

Restarting httpd got rid of these, but two weird things happened:

1. At first, it appeared that the temporary schemas were still in my browser after the httpd restart (maybe a caching issue).

2. The schemas remained in the database.

I'm not sure there's any reason to include any schema owned by Postgres in the catalog.

**Comment by karlcz** [comment]
it seems like the `public` namespace is often owned by `postgres` so I guess we'd have to exclude it from this rule...

**Comment by karlcz** [comment]
would it be any less hacky to just exclude namespaces that match the `pg_temp_.*` or `pg_toast_temp_.*` naming schemes?

**Comment by karlcz** [comment]
A fix for this is pushed to master to exclude based on the standard temp schema naming patterns
