### ISSUE TITLE
Allow both paging modifiers at once

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#175]
There are use cases for getting rows *between* both an upper and lower bound, which ermrest currently does not allow.

1. `@after` alone means the result stream *after* the given lower bound
2. `@after` with `limit` means the first page *after* the given lower bound
3. `@before` with `limit` means the last page *before* the given upper bound

We can add the following cases without ambiguity:

- `@after` with `@before` means the result stream *between* the two bounds
- `@after` with `@before` and `limit` means the first page *after* the lower bound which is also capped by the upper bound  (the lesser of the page-limit and the upper bound is the effective bound for the page)

@hongsudt @RFSH @robes

**Comment by karlcz** [comment]
This is implemented in the ermrest/stateful-model branch.

**Comment by RFSH** [comment]
@karlcz Do both of these `after` and `close` define closed intervals? So `@after(1)@before(1)` will return zero results, right?

**Comment by karlcz** [comment]
That's right, the boundaries are exclusive to the requested range.

**Comment by karlcz** [comment]
I cherry-picked this one commit from the stateful-model branch and pushed it on master so it can be used by deployments before that other PR is merged...
