### ISSUE TITLE
Binning not supported for system columns

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrest#188]
When making a `bin` request to the `attributegroup` API with the `RMT` or `RCT` column, an error is thrown from `ermrest`.

For example:
https://synapse-dev.isrd.isi.edu/ermrest/catalog/1/attributegroup/M:=Zebrafish:Segmentation%20Mode/c1:=bin(RMT;10;2017-09-13T06%3A12%3A56-07%3A00;2017-09-13T06%3A12%3A56-07%3A00);c2:=cnt(*)

returns:
```
409 Conflict
The request conflicts with the state of the server. Binning not supported on column type ermrest_rmt.
```

**Comment by karlcz** [comment]
This was a general issue of not considering base types for domains when deciding whether to provide type-specific features.  This is patched in both master and stateful-model branches.

**Comment by jrchudy** [comment]
This is working properly now.
