### ISSUE TITLE
Binning not supported for Timestamp columns

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrest#189]
When making a `bin` request to the `attributegroup` API with a column of the type `timestamp`, an error is thrown from ermrest. This works as expected for columns of type `timestamptz`.

```
message: 'Binning not supported on column type timestamp.',
subMessage: '409 Conflict. The request conflicts with the state of the server. Binning not supported on column type timestamp.'
```

**Comment by karlcz** [comment]
Right, this isn't currently supported.  It seems like it will be a pretty trivial patch to enable it.

However, we don't have any good way to do feature detection to determine whether the enhancement is present. I wonder if the Chaise default should disable the histogram feature for this column type, but allow the DBA to enable it explicitly on a column?  Later on, we could change the default if we are no longer concerned about continued support for older ermrest deployments...

**Comment by karlcz** [comment]
Support for binning of timestamp has been pushed to master and stateful-model branches

**Comment by jrchudy** [comment]
Binning for columns of type `timestamp` is working as expected on `master` branch. 

For deciding whether to show the histogram, we consider the annotation first then verify if the column  type is supported. This could be changed if we want to specifically for `timestamp` but it doesn't appear to cause any issues leaving it "always available".
