### ISSUE TITLE
Array aggregation not supported on custom domain types

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrest#190]
For example an aggregation on a RID will return:

```
409 Conflict
The request conflicts with the state of the server. could not find array type for data type ermrest_rid
```

**Comment by karlcz** [comment]
This exposes a real limitation of postgresql in that one cannot form an array of a domain type.  If we want to support array aggregation, we would need to cast the domain value to a type which supports it. There are three main cases to consider:

1. domains over basic scalar types: we could cast to the underlying type and then array aggregate those values
2.  domains over json/jsonb: these act much like scalar types and can be aggregated if we strip the domain, and the UX may feel like it produces nested arrays
3. domains over array types: these cannot be array aggregated even if we strip the domain, but in practice they can be round-tripped through JSON or they wouldn't be useful domains with ermrest protocol and Chaise clients

The enhancement with the least surprises might be to:
- Handle case 1 and 2 of scalar values by casting the domain value to the base scalar type
- Handle case 3 by converting the domain value to a jsonb value

**Comment by karlcz** [comment]
I pushed changes for this in the stateful-model branch, following the technique described above to look through domain types to their underlying types and to convert arrays into jsonb so we can have nested arrays of arrays if needed in an aggregate result.
