### ISSUE TITLE
Extra Aggregate Functions

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrest#192]
With the addition of pseudo-columns in ermrestjs, new aggregate functions are needed. These are the aggregate functions that we think might be useful:

- `avg`
- `array_d`: same as current `array` aggregate function but only returns distinct values.

**Comment by karlcz** [comment]
I pushed support for `array_d` and `avg` in the stateful-model branch.  This also includes enhancements for the related #190 issue so you can get arrays of RID etc.
