### ISSUE TITLE
Performance tuning

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrest#193]
generate better sql:

- Simplify `(SELECT ... FROM foo as t0 WHERE ((True))) AS t0` to just `foo AS t0`
- Simplfy policies like `(SELECT True FROM foo AS t0t1 WHERE (t0.RID = t0t1.RID) AND (t0t1.x = 'x') LIMIT 1)` to just `t0.x = 'x'`

**Comment by ljpearlman** [comment]
just adding a note that the reason for this is that without these changes, postgres doesn't subset queries with group by / order by / limit until after doing all the left joins.

**Comment by karlcz** [comment]
I think recent commits addressed these concerns (at least as well as we're going to be able to for now).
