### ISSUE TITLE
Scalar-aggregate subqueries in projection lists

### ISSUE THREAD

**Issue by mikedarcy** [informatics-isi-edu/ermrest#2]
Add some syntax for scalar subqueries, to allow multiple independent aggregates to be projected for the same result entity (or group) without producing a cross-product of input rows between the different aggregates.

**Comment by karlcz** [comment]
I'm not sure if this is  a wishlist thing. It seems like we have been working around it with views instead...?

@hongsudt @carlkesselman @robes @bugacov

**Comment by karlcz** [comment]
Closing this stale issue.
