### ISSUE TITLE
array_d In Entity Mode

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrest#206]
Can we use `array_d` or `cnt_d` aggregate functions in entity-mode? Currently ermrest throws the following error:

https://dev.rebuildingakidney.org/ermrest/catalog/2/attributegroup/M:=Protocol:Protocol_Author/T:=left(Protocol)=(Protocol:Protocol:RID)/RID=N-H9A4/c:=RID;v:=array_d(M:*)
```
Failed: 400 Bad Request
The request is malformed. Aggregate function array_d not allowed on star column.
```

**Comment by karlcz** [comment]
I've pushed a fix to allow this case.

**Comment by RFSH** [comment]
@karlcz What about `cnt_d`? Does that make sense in entity mode? It's throwing the same error.
