### ISSUE TITLE
ermrest exposes keys consisting of invisible columns

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#216]
Here is the link to the schema:
https://dev.rebuildingakidney.org/ermrest/catalog/2/schema/RNASeq/table/Study/

Curation_Status is hidden, but the key consisting of this column is included in the schema.

**Comment by karlcz** [comment]
Confirmed. This is specific to a non-enumerable column that also has a dynamic ACL binding for select.

**Comment by karlcz** [comment]
I think that a workaround for this corner case is to set a `scope_acl` on the column's ACL bindings which is no more broad than the `enumerate` static ACL for the column.  This should make ermrest ignore those ACL bindings for clients not meant to be aware of this column, and avoid the bug.

**Comment by karlcz** [comment]
A fix was pushed to the py3 branch.

**Comment by karlcz** [comment]
The fix was also cherry-picked and pushed to master.
