### ISSUE TITLE
Stale cache hit on catalog object

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#219]
An incorrect `304 Not Modified` response has been observed for, e.g., `GET /ermrest/catalog/1` from a browser after a record in the catalog has been changed.

Using shift-reload on the browser will retrieve the updated catalog description which reflects an updated snaptime value for the catalog. The regular retry should have responded 200 OK w/ this revised value.

**Comment by karlcz** [comment]
It looks like the top-level catalog API was using the model snaptime rather than the catalog snaptime to formulate its ETag value.

**Comment by karlcz** [comment]
I've pushed a fix. @jrchudy  can you confirm this also fixes it for you, then close this issue?

**Comment by jrchudy** [comment]
I can confirm that this is now fixed on both synapse-dev and dev.isrd when caching is enabled.
