### ISSUE TITLE
SQL errors from ermrest when creating tables.

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrest#224]
I'm getting SQL errors when I try to create a table on any of the rbk hosts (but not all the time -- there seem to be some very simple test cases that will work some of the time).

 I upgraded all the rbk hosts to fedora31/postgres12 this week, and this is probably the first time since then that anyone's tried to create a table. I used pg_upgrade to upgrade postgres). I'm not sure whether this is an ermrest/pg12 problem, some weird database corruption, a bug in my client code, or what.

 For example, I get this when I run [add_3d_table.py.txt](https://github.com/informatics-isi-edu/ermrest/files/4634261/add_3d_table.py.txt)
 (the weird .txt extension is there because git won't let me upload a .py file):

```
laura$ python3 add_3d_table.py.txt -c 2 www.rebuildingakidney.org
Traceback (most recent call last):
  File "add_3d_table.py.txt", line 64, in <module>
    main(args.host, args.catalog, credentials, args.schema, args.table)    
  File "add_3d_table.py.txt", line 54, in main
    schema.create_table(table_def)
  File "/Users/laura/anaconda3/lib/python3.7/site-packages/deriva/core/ermrest_model.py", line 166, in create_table
    json=table_def,
  File "/Users/laura/anaconda3/lib/python3.7/site-packages/deriva/core/deriva_binding.py", line 304, in post
    return self._raise_for_status_412(r)
  File "/Users/laura/anaconda3/lib/python3.7/site-packages/deriva/core/deriva_binding.py", line 210, in _raise_for_status_412
    _response_raise_for_status(r)
  File "/Users/laura/anaconda3/lib/python3.7/site-packages/deriva/core/deriva_binding.py", line 105, in _response_raise_for_status
    response=self
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: [https://www.rebuildingakidney.org/ermrest/catalog/2/schema/Gene_Expression/table] Details: b'409 Conflict\nThe request conflicts with the state of the server. null value in column "table_rid" violates not-null constraint\nDETAIL:  Failing row contains (2020-05-15 04:41:10.616723-07, null, https://auth.globus.org/a4e03698-d274-11e5-9a48-8b6f49eb5587).\nCONTEXT:  SQL statement "INSERT INTO _ermrest.table_modified (table_rid, ts) VALUES ($1, now())\n  ON CONFLICT (ts, table_rid) DO NOTHING\n  RETURNING ts"\nPL/pgSQL function _ermrest.data_change_event(text) line 5 at SQL statement\nSQL statement "SELECT _ermrest.data_change_event(t_rid)"\nPL/pgSQL function _ermrest.record_new_table(text,text) line 19 at PERFORM\n\n'
```

**Comment by karlcz** [comment]
Hmm, the specific error suggests something is very inconsistent about
your database.  The function being called is a normal step in creating
new tables and recording them in the _ermrest schema. These functions
are all in ermrest/ermrest/sql/ermrest_schema.sql if you are
interested in reading the code. The call stack looks like:

1. Python service code
2. plpgsql func: _ermrest.record_new_table(schema_rid, table_name)
3. plpgsql func: _ermrest.data_change_event(table_rid)
4. SQL stmt: INSERT INTO _ermrest.table_modified ... VALUES (table_rid, now())

Most significantly, the table RID passed as argument to
data_change_event in (3) is NULL according to the error text you
sent. But, this value is computed earlier in straight-line code within
the calling function (2). I don't see how it could be NULL nor how
those lines could have completed without error if it were somehow
generated as NULL...

I will also note that I saw postgres crashes on my production host
days after upgrading to 12.  I had to drop my production DB and
restore it from a backup to get it working.  It seemed like postgres
internal structures were corrupted and broke badly with write
transactions.

**Comment by ljpearlman** [comment]
For the record, here's what I did to get it to work on rbk-dev and staging (production had additional problems);
1. shut down httpd, dump all the (psql-12) databases*
2. uninstall psql-12 and remove the psql-12 data directory structure
3. reinstall psql-12, initdb,
4. run 55-software-deploy.sh, restore databases
5. run _ermrest.model_change_event() 
6. run ermrest-deploy (not sure if I need this here, since it was run in step 4)
7. restart httpd

I did basically the same thing on production, except the _ermrest_model_change_event() failed. So at that point, I did this:
6. run _ermrest_model_change_event_by_oid()
7. run ermrest_deploy
8. start httpd
9. notice that it's not working at all and I'm getting a lot of error messages of RIDs/RCTs/RMTs in views not having non-null constraints.
10. add those in (via sql, since the ermrest server wasn't working at that point)
11. run _ermrest.model_change_event()
12. start httpd

*for dev/staging I just used existing dumps (v12 for staging, v11 for dev because I foolishly blew away all the v12 dumps when I removed the v12 data directory)

**Comment by karlcz** [comment]
Unfortunately, it was a big mistake to do model_change_event_by_oid.
That probably corrupted your model and you should drop and reload
again.  That function is to resolve any inconsistency in oid->name by
assuming OIDs are already in sync and resolving differences as
rename/add/remove.  You could get very strange effects all over the
model doing that after a dump/restore, where the OIDs are very much
not in sync.

The issue with model_change_event (which is by name) failing is due to
it being fragile when the new OIDs issued overlap with the ones in the
dump you restored.  Since postgres issues these via sequence, they
will increase and should eventually not collide if you repeat the
model_change_event until it succeeds.

Over the years, there have been various changes in ermrest to try to
make this smoother. It makes _ermrest schema's fkey constraints
DEFERRABLE, but I don't know that those changes are in your dump of a
legacy catalog, so it may or may not help.  If they are present, you
could set all constraints deferred mode in a transaction before
running model_change_event and see if it helps sort things out in
fewer attempts...

Karl
