### ISSUE TITLE
The server does not recover from an invalid acl binding during model introspection

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/ermrest#225]
I have defined:
```
entry_workflow_status_acl_binding = {
  "submit_reader": {
    "types": [
      "select"
    ],
    "scope_acl": [
      "https://auth.globus.org/99da042e-64a6-11ea-ad5f-0ef992ed7ca1"
    ],
    "projection": [
        {"or": [
            {"filter": "Workflow_Status", "operand": "PDB:1-MSVE", "operator": "="},
            {"filter": "Workflow_Status", "operand": "PDB:1-MSVM", "operator": "="},
            {"filter": "Workflow_Status", "operand": "PDB:1-MSVG", "operator": "="}
            ]
        },
      "RID"
    ],
    "projection_type": "nonnull"
  }
}
```
After running:
```
fk.acl_bindings.update(entry_workflow_status_acl_binding)
model_root.apply()
```
the command:
```
model_root = catalog_ermrest.getCatalogModel()
```
raises the exception:
```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: [https://pdb.isrd.isi.edu/ermrest/catalog/99/schema] Details: b"400 Bad Request\nThe request is malformed. ACL binding type 'select' is not supported on this resource.\n"
```

**Comment by karlcz** [comment]
This is really two bugs in one.  I am renaming this issue to the first bug, which has already been patched in ermrest/master.  The server will now recover from such situations with the same 503 Service Temporarily Unavailable recovery sequence which we have used elsewhere. The introspection will detect the inconsistency, purge the bad policy, and use this error to signal via HTTP that a client will need to retry their request. The next time around, things should work again.

I opened #226 to capture the second bug, which is that the server let you submit an invalid acl binding in the first place, not returning an immediate error.
