### ISSUE TITLE
ERMRest returns 500 when trying to create an fkey that already exists

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrest#240]
This should probably be a 409, not a 500.

**Comment by karlcz** [comment]
Is this related to the deriva-py issue you filed which was talking
about creating a pseudo foreign key on a view and then trying
to update annotation+policy config afterwards?

**Comment by ljpearlman** [comment]
Yes, sorry, this probably only happens with views / pseudo-kfeys

**Comment by karlcz** [comment]
Is this something you remember how to test? If not, I am thinking of closing this issue as non-reproducible... 

I think some related bugs were patched in the flask refactoring, but I am not sure what it would take to reproduce the scenario you reported.

**Comment by karlcz** [comment]
This should be fixed by a recent merge that also improved generation of constraint names.
