### ISSUE TITLE
ERMrest returns Bad Request error for tcrs in a table with many columns

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrest#241]
As title suggests, using `tcrs` in a table with many columns is throwing a bad request error. 

To replicate this, I navigated to the following page while being logged in:

```
https://dev.rebuildingakidney.org/ermrest/catalog/2/attributegroup/M:=Gene_Expression:Image/id=14-47YP/RID;M:=array_d(M:*),tcrs:=tcrs(M:RID)@sort(RID)?limit=2
```

And the response is:

```
400 Bad Request
The request is malformed. cannot pass more than 100 arguments to a function
LINE 9: ...lete'::text, True::boolean,'column_update'::text, jsonb_buil...
                                                             ^
```

There are 54 columns in this table and that might be causing this issue. Accessing the same url anonymously (where 50 columns are visible) doesn't throw any errors and works properly.

**Comment by karlcz** [comment]
This has been fixed in master, by building the object in batches and using postgres jsonb concatenation operators to merge the per-batch objects.
