### ISSUE TITLE
Fkey ACL change attempts fail with 500 errors

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrest#243]
The easiest way to reproduce this is probably to just do:
```
table = model.table(sname, tname)
table.apply()
```
on a table with foreign keys.

This isn't a high priority -- I don't actually need to change any foreign key ACLs. This is just something I stumbled across.

**Comment by karlcz** [comment]
Please provide more information.  I have working projects that apply changes at table, column, and fkey nodes of a model while reconfiguring a catalog...

**Comment by karlcz** [comment]
Closing this old issue for lack of detail and ability to reproduce. If you encounter problems like this again, please open a new issue and try to include error/stack information from the server logs.
