### ISSUE TITLE
databases_backup.sh (aws-recipe-basic version) skips persistent databases on installations without simple_registry

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrest#256]
The databases_backup.sh script has this:

```
# on this dev host, we mark "persistent" catalogs by setting created_on to null...
DATABASES=(
  $(su -c "psql -A -t -q -c \"SELECT descriptor->>'dbname' FROM ermrest.simple_registry WHERE created_on IS NULL\"" - ermrest)
)
DATABASES+=(
    webauthn
    ermrest
    hatrac
)
```

which means that if a deployment doesn't have ermrest.simple_registry,  only the webauthn, ermrest, and hatrac databases will be backed up. So the script should probably check both simple_registry and registry -- although the comment looks like maybe this was intended only for test systems like dev.isrd, so maybe it should check for that somehow instead. Or maybe it would be safer to default to backing up all databases and produce a list of exclusions.

**Comment by karlcz** [comment]
This issue is not about the ermrest codebase but some stale, externally maintained backup script.
