### ISSUE TITLE
Support the GET method of the Catalog collection resource

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrest#26]
New REST operation to get a listing of all catalogs.

__Request__
```
GET catalog
```

__Response body (json only)__
An array of a catalog representations. However, these representations are somewhat minimal compared to what you would get from a `GET catalog/N` because we only want to return the minimal info that is in the registry and not have to go and open a connection to ever database that the ERMrest service knows about.
```javascript
[ { 'id': 'name', ... }, ... ]
```

__Access Control__
I think we should have a top level ACL to permit listing of all catalogs. Like this in `ermrest_config.json`:

```javascript
...
  'registry' : {
    ...
    'acls': {
      'list_catalogs_permit': [ roles+ ],
      ...
    }
...
```
My thinking is that we should not rely on the per-catalog ACLs to permit listing of the catalog. That would require opening a connection to every catalog's database and reading its ACLs.

__Limitations__
The `registry` module (i.e., `registry.py`) defines an interface and base implementation `Registry` and the `SimpleRegistry` implementation, which is the one and only implementation of a registry we have ever had. The above feature may only work in a "simple" registry such as our current one that keeps a record of all catalog-database mappings in its own database. In the unlikely event that we supported some other registry implementation (like a distributed hash table based implementation) then this operation might not be implementable. The server should be able to respond with the No Method response (not Internal Error) and clients should be aware that this method might not be supported.

**Comment by karlcz** [comment]
It should either be an array of catalogs [{"id": 1}, ...]
or a mapping like { 1: {"id": 1}, ... }.

I think I'd prefer the array but I'm not sure.

**Comment by robes** [comment]
I prefer array actually. That was a mistake.

**Comment by karlcz** [comment]
One question is whether we should have per-catalog listing ACLs inside the descriptors or registry itself... I'm not sure if all catalogs should always be under the same static policy here.

**Comment by robes** [comment]
good question. just don’t want to overlap or duplicate what we do with the catalog’s `read_acl`.

**Comment by karlcz** [comment]
We'd also need a REST interface to manage this ACL unless we overload
it on the catalog/meta/ API and just match one magic ACL name and
route it over to the registry instead of handling it in the catalog...

**Comment by robes** [comment]
What use case do you have in mind for this per-catalog listing ACL? versus a simpler service-level listing ACL that applies across all catalogs?

**Comment by karlcz** [comment]
It's not so much that I have a use case as I don't understand the
utility of exposing catalogs that the user will be forbidden to view
anyway (since we have per-catalog access ACLs already).

On reflection, I am actually not sure what the value of this listing
mechanism is at all for regular users.  You're just going to get back
catalog numbers, right?  There will be no other information to help
understand the purpose of the catalog.

So the real question might be: what additional content is needed in
catalog descriptors so that we can have a useful listing mechanism?
That could include both descriptive metadata and ACLs so that the
resulting list is meaningful and actionable.

**Comment by robes** [comment]
Well right. I had in mind we would want to add a human readable description.

**Comment by robes** [comment]
The more I think about this feature the less inclined I am to want us to implement it at this point. We are either going to hack something badly and/or redevelop a bunch of features that are already in ERMrest. We've joked in the past that the registry should maybe be implemented as a reserved catalog (i.e., `catalog/registry/...`). Ultimately won't we want to: query and filter the catalog registry, limit the results set (so we don't get back a listing of 1 million catalog descriptions), and so on? And conceptually, isn't the _registry_ just a _catalog of catalogs_ really?

**Comment by robes** [comment]
Would there be value in this feature for UI clients (such as the one UC is developing) that want to let users select the catalog. I think we will need that feature. So in addition to my original comment:

- each catalog has a `description` field in the registry that is returned along with the catalogs `id`
- each catalog entry in the registry has a `list_acl` for per-catalog listing access control

Optionally if we want to support the listing of deleted but not yet purged catalogs the interface would support a `show_deleted` query option. E.g.,

```
GET catalog?show_deleted=True
```

If that's the case then we also return the `deleted_on` field along with the id and description of the catalog.

With regard to my last comment about whether this would be a bad hack. I was rethinking that opinion. The internal implementation which was divided between an abstract interface `Registry` and the `SimpleRegistry` implementation was also intended to support just that a _simple_ registry implementation while leaving open the possibility for more sophisticated implementations in the future. So I think its fine to have limitations that are clearly described in our documentation. I.e., don't GET catalog if you have a million of them, or implement a better registry.

**Comment by robes** [comment]
I'm going to mark this "wont fix". We can always reopen it in the future.
