### ISSUE TITLE
PoolError: trying to put unkeyed connection

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/ermrest#27]
While starting chaise for the facebase database, multiple stack traces are logged: 

[Wed Aug 19 15:04:27 2015] [error] [client 128.9.128.164] mod_wsgi (pid=9667): Exception occurred processing WSGI script '/usr/lib/python2.6/site-packages/ermrest/ermrest.wsgi'.
[Wed Aug 19 15:04:27 2015] [error] [client 128.9.128.164] Traceback (most recent call last):
[Wed Aug 19 15:04:27 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/web.py-0.37-py2.6.egg/web/application.py", line 605, in wrap
[Wed Aug 19 15:04:27 2015] [error] [client 128.9.128.164]     yield next()
[Wed Aug 19 15:04:27 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/web.py-0.37-py2.6.egg/web/application.py", line 597, in next
[Wed Aug 19 15:04:27 2015] [error] [client 128.9.128.164]     return result.next()
[Wed Aug 19 15:04:27 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/ermrest/sanepg2.py", line 157, in perform
[Wed Aug 19 15:04:27 2015] [error] [client 128.9.128.164]     self.used_pool.putconn(self.conn, close=True)
[Wed Aug 19 15:04:27 2015] [error] [client 128.9.128.164]   File "/usr/lib64/python2.6/site-packages/psycopg2/pool.py", line 171, in putconn
[Wed Aug 19 15:04:27 2015] [error] [client 128.9.128.164]     self._putconn(conn, key, close)
[Wed Aug 19 15:04:27 2015] [error] [client 128.9.128.164]   File "/usr/lib64/python2.6/site-packages/psycopg2/pool.py", line 98, in _putconn
[Wed Aug 19 15:04:27 2015] [error] [client 128.9.128.164]     raise PoolError("trying to put unkeyed connection")
[Wed Aug 19 15:04:27 2015] [error] [client 128.9.128.164] PoolError: trying to put unkeyed connection

The returned results are not affected.

**Comment by karlcz** [comment]
This seems to require concurrent data API requests in order to reproduce.
