### ISSUE TITLE
Version the database schemas to support upgrade logic

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrest#29]
We should consider adding some versioning to the `ermrest` database so that the deployment scripts can use this versioning information in order to automatically upgrade the database. We might do this by simply adding a `ermrest.version` table to the schema.

**Comment by karlcz** [comment]
Should probably do this for both registry and catalog databases, and
follow a convention for upgrade scripts named by their logical
version.

Should each upgrade script for version N apply only if DB is in state
N-1?  Or should an outer driver script just check the DB version and
apply the sequence of update scripts to get it from M to N?

**Comment by robes** [comment]
Right, and applied in sequential order to upgrade the registry and catalog database.

On August 20, 2015 at 11:37:02 AM, karlcz (notifications@github.com) wrote:
Should probably do this for both registry and catalog databases, and
follow a convention for upgrade scripts named by their logical
version.

Should each upgrade script for version N apply only if DB is in state
N-1? Or should an outer driver script just check the DB version and
apply the sequence of update scripts to get it from M to N?

**Comment by karlcz** [comment]
In PR #65 I started making ermrest-deploy more idempotent.  I suggest that we continue this and make it the protocol for upgrades.  A fresh deploy should work as expected, and a redeploy should make every effort to upgrade the registry and any registered catalogs to the current version while preserving content.

**Comment by karlcz** [comment]
I'm closing this old issue since we seem to have lived without it via a more duck-typed/structural upgrade process.
