### ISSUE TITLE
Add response header reporting entity-type of addressed resources

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#39]
Would it be useful to return a custom header with the entity-type of the addressed resources?  For example: `X-ERMrest-Entity-Type: S:T` or `X-ERMrest-Entity-Type: /ermrest/catalog/N/schema/S/table/T` (to make it a URL referencing the model element).

This would be useful in `/entity/...` API requests such as GET and HEAD where a complex entity-path makes it difficult to determine the addressed entity type without parsing and analyzing the whole path with respect to the catalog model.  Of course, a client constructing such a path ought to already know the semantics. This is most useful in reentrant scenarios like bookmarking or referrals where a client is given an ERMrest URL or URL fragment and needs to bootstrap its own understanding of the referenced data.

It might also be relevant in other APIs like `/attribute/` to indicate the entity path context from which the attributes are drawn. However, this would NOT mean that the response content itself conforms to the entity type. Perhaps there should be separate headers for this, if any at all?

**Comment by karlcz** [comment]
A different way of looking at this would be to denormalize some schema information into response headers.
1. This could reduce client latency for simple requests by embedding the table description in the same response with the data.
2. This could provide the anonymous record type information to describe projected query results from aggregate, attribute, and attributegroup queries.

**Comment by karlcz** [comment]
@robes @hongsudt @shinyichen As we analyze more GUI requirements, it seems to me that server-side support as described in this issue is never going to be sufficient.
We really need the clients (such as ermrestjs) to understand the semantics of ERMrest resource URLs, be able to serialize/deserialize them, and be able to "reason" about them in terms of composition *and* decomposition.
There is little you can do to support realistic UX around reentrant/bookmarkable apps for query editing, automatic navigable links, nor catalog content editing without making the client side aware of these semantics and protocol issues.  You need to understand table instances, entity-path linkage, column instance references, the set cardinalities and semantics of the base APIs, etc.
Thus, I think we should focus on developing the client-side capabilities and gaining experience with them, rather than piling features into the protocol that we then might have to support for backward compatibility even when they prove insufficient for our typical apps.  Thoughts?

**Comment by robes** [comment]
I agree. It seems inevitable that we need the client side to understand the semantics of the ermrest URL. So, yes, let’s not start adding to the protocol.
