### ISSUE TITLE
Spec out vocabulary meta-model

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrest#42]
We want to have uniform way of representing vocabulary which should include support for description, synonym and relationships.

**Comment by robes** [comment]
not sure who should be the reviewer. either karl or carl.

**Comment by robes** [comment]
the best place to look at this is in the data-commons project where the isa common model designs are committed.

**Comment by karlcz** [comment]
My two concerns:
1. Not sure the purpose of the `vocabulary` level table nor having `vocabulary_id` foreign keys in the concept level table. I expect there to be a separate concept table for each distinct vocabulary, with all rows of the table being from the same vocabulary. Thus, I'd turn the `vocabulary` entity content into an annotation on a particular concept table rather than allowing individual rows to associate to vocabularies.
2. I think synonyms need to be present in the same concept table under the same uniqueness constraint so that there cannot be collisions between base terms and synonym terms due to invalid table content and so that foreign key references to terms are possible since not all referencing tables will be fully normalized. So, I'd make a nullable foreign key reference similar to the `parent` reference to have a synonym reference its own canonical concept.

**Comment by robes** [comment]
Chiming in here on Karl's comment. I agree with the first point. For the second point, how about just making the synonym table an association table (mapping concept-to-concept within the same concept table).

**Comment by robes** [comment]
I factored out the vocabulary meta-model into its own diagram and made updates per the earlier suggestions in this thread.

https://github.com/informatics-isi-edu/data-commons/blob/master/models/vocab-metamodel.pdf

**Comment by hongsudt** [comment]
The vocab table is very complicated. Most of the fields will be null in
many cases. Can we simplify it or have 2 different versions? Or start with
a simple version and if needed add more columns later?

**Comment by carlkesselman** [comment]
I would prefer not.  We already have use cases with RBK where we want subclassing and synonyms.  Also Facebase anatomy.  We really need to push on this.  I would not suggest two versions, as we never start working out the UI issues that we have to.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 10, 2016, at 6:55 PM, Hongsuda <notifications@github.com<mailto:notifications@github.com>> wrote:

The vocab table is very complicated. Most of the fields will be null in
many cases. Can we simplify it or have 2 different versions? Or start with
a simple version and if needed add more columns later?

**Comment by karlcz** [comment]
As per some email discussions and my latest review of the PDF mentioned by @robes:
1. I think parent_id and synonym_id should both be dropped as predefined columns (see next item).
2. I think annotations are needed to mark two *kinds* of hierarchical column, where each one can be instantiated zero or more times on a single vocabulary. A further generalization would be an annotation to identify relations encoded in external tables, e.g. for non-hierarchical relations or for relations between different vocabularies or subsets.
  - Hierarchical parentage: the generalization of parent_id, i.e. direct ancestor in some named hierarchy
  - Hierarchical top: the generalization of synonym_id, i.e. transitive ancestor in some named hierarchy
3. Not every vocabulary has/needs all of id, code, uri.  What subsets and/or default rules can be defined to consistently define or fake these?
4. It keeps bugging me that we don't know whether particular projects/apps would want all terms in one vocabulary table or not.  How can we juggle different subset domains to allow appropriate foreign key constraints to be defined for each use case?
5. Very few vocabularies have validity periods and invalidation reasons. I'm not sure why we'd put such esoterica in our systems when there is very little useful UX we can build around them.

**Comment by cmungall** [comment]
Some comments on the PDF above:

 * Assumes zero or one parents term concept. Most ontologies are graphs (with labeled edges)
 * 'codes' is terminology that is specific to some medical systems. There are a variety of identifier schemes and meta-schemes. We find that CURIEs provide a nice unifying mechanism for relating shortform IDs/codes to the official semweb URI
 * @robes and I discussed the use cases for making a separate table for each vocabulary source. I am skeptical about the utility of using foreign keys as constraints here, semantic constraints may prove more useful here 

For an example of a relational schema that supports a variety of ontology metamodels, see the controlled vocabulary module in Chado: http://gmod.org/wiki/Chado_CV_Module

In particular the two tables:

 * [cv](http://gmod.org/wiki/Chado_CV_Module#Table:_cv)
 * [cvterm](http://gmod.org/wiki/Chado_CV_Module#Table:_cvterm)

It would be easy to map the SQL DDL to the ermrest schema definition language, and plop in these with every ermrest instance

Also worth looking at metamodels such as LexGrid. If you want to get really meta there is a UML OWL metamodel out there but that may not be a useful level of abstraction for you.

**Comment by robes** [comment]
I realize now this issue is sort of in the wrong repo... Its sort of misleading to call this an ERMrest issue other than we want to define an annotation in the ERMrest guide so that applications can understand how to interpret parts of an ERMrest schema as vocabulary. We never intended to imply that we would bake in a vocabulary meta-model into the ERMrest protocol. My mistake.

That aside, I like what I see in the Chado CV module and it is probably better for many of our use cases than OMOP, so it may be a better template to follow or borrow from. @cmungall, Is there a way to get the SQL DDL for the Chado CV Module? I looked across the gmod.org site and didn't find it although I do see instructions for getting the whole stack of software (I believe). Even better would be to also get an exemplar vocabulary to populate it with so we could play around with ERMrest queries over it. Any pointers would be appreciated.

**Comment by cmungall** [comment]
Schema:
https://github.com/GMOD/Chado/blob/master/chado/modules/cv/cv.sql

@scottcain may be able to help with some of the other questions. There is a truly contorted loader I wrote years ago that goes obo->xml, xml->db via a custom protocol called xort/stag, I think @kimrutherford has something much better (is that in the gmod stack yet?)

It should be possible to get some example dumps or open postgres ports to play with. See for example: http://flybase.org/static_pages/feature/previous/articles/2013_12/precomp_files_sql_querying.html 

Any of the vocabs you use should work, though it will only support the obo subset, which is fine for your purposes (unless you plan on implementing reasoning within sql...)

**Comment by kimrutherford** [comment]
> I think @kimrutherford has something much better (is that in the gmod stack yet?)

Hi.  We have a prototype OBO -> Chado loader here: https://github.com/pombase/chobo/

It's not in GMOD yet and we haven't announced it.  It works for us but isn't general enough to help
others yet.  For example it doesn't cope with every OBO file yet.  There are a lot of corner cases that the code doesn't handle yet, but we're working on it.

It's in CPAN so can be installed with:
    cpanm PomBase::Chobo

The latest version is 0.005, released a few minutes ago.

> It should be possible to get some example dumps or open postgres ports to play with.

PomBase is much smaller than FlyBase so our Chado Postgres dumps are much smaller if anyone is just looking for something to play with:
  https://curation.pombase.org/releases/pombase-chado-v60-2016-05-12/pombase-chado-v60-2016-05-12.dump.gz

That dump was made from Postgres 9.5 but we aren't using any fancy new features so it should work with older versions.

**Comment by karlcz** [comment]
I copied some [notes on Chado and ERMrest](https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/Chado-patterns.md) from another location so it is easier to share and discuss...

**Comment by karlcz** [comment]
@robes  I think this old issue is obsoleted by the slimmed down vocabulary table convention we've started to follow with the model-management helpers in deriva-py.  Shall we close this?

**Comment by robes** [comment]
yeah
