### ISSUE TITLE
Table level 'row_name'

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrest#43]
Extend the display annotation on tables with a way of naming the row. A `row_name` can also take the place of what we used to call the `title`. Meaning a `row_name` is a valid way of forming a `title` when a title is needed. A `row_name` can also be used in different contexts like in the selection control of a data entry form for picking a foreign key.

**Comment by robes** [comment]
See this:
https://github.com/informatics-isi-edu/ermrest/blob/annotation-update/user-doc/annotation.md#2015-display

**Comment by karlcz** [comment]
I merged this PR so not sure this needs further review.  I think a separate issue covers implementation of the feature.
