### ISSUE TITLE
Add page-key syntax to simplify paging

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#48]
To assist applications with complicated sort criteria and paged access, define a new modifier syntax to complement `@sort(...)` with a content-based offset into the sorted stream. The `limit=N` query parameter may be required when using these features, to ensure that the requested work is not too expensive.

## New URL modifiers

- `@after(...)`: get page of rows following the last observed row-key that goes in place of the ellipsis.
- `@before(...)`: get page of rows preceding the last observed row-key that goes in place of the ellipsis.

These new modifiers are only allowed *after* the `@sort(...)` modifier in the URL. The sort is defined as an ordered sequence of output columns and sort directions.  A comma-separated list of values specifies the column values for the page key corresponding to each part of the sort. Allow `::null::` to specify a NULL, retaining the normal mapping of empty string to empty string as in the predicate language.

It is the client's responsibility to include a unique key in the sort key, so that every row key is unique for the purpose of sorting and splitting results into pages without ambiguity.

## Concurrency-aware pagination

1. Fetch initial page with `...@sort(...)?limit=N`
2. Fetch _subsequent_ pages with `...@sort(...)@after(...)?limit=N` where the `after` key values come from the final row of the antecedent page.
3. Fetch _antecedent_ pages with `...@sort(...)@before(...)?limit=N` where the `before` key values come from the first row of the subsequent page.

Realize that a sequence of forward and backward page requests through a dataset might not land on the same page boundaries on both visits!

- Rows might be inserted during a traversal. An inserted row MAY appear in the traversal or MAY be skipped depending on where it falls in the sorted sequence.
- Rows might be deleted during a traversal. A deleted row MAY appear in the traversal or MAY be skipped depending on where it falls in the sorted sequence.
- Rows might be mutated such that they change positions in the sorted sequence during a traversal. A mutated table row contains one tuple of data before the mutation and another tuple of data after. A single traversal concurrent with that mutation MAY encounter zero, one, or two copies of the row depending on where they fall in the sorted sequence.

**Comment by karlcz** [comment]
Can @robes and @shinyichen review the issue description above and see if this seems sufficient and worth implementing as an ERMrest enhancement. It only seems useful if we can build ermrestjs pagination on top of it, i.e. provide a stateful rowset abstraction that lets you get more pages of data via promise-based APIs.  I included support for paging in both directions with the idea that we can eventually have proper scrolling in our apps, i.e. a fixed window size of data buffered and displayed in the app and retrieving antecedent or subsequent pages on demand.

**Comment by robes** [comment]
I fixed one typo in your description above -- the `@before(...)` keyword.

One question, does this ever make sense to use without the `limit=N` option? I assume, no.

**Comment by karlcz** [comment]
I think it would be meaningful but we might want to disallow it to
let postgres do faster query plans.

More or less these before/after modifiers will translate into
additional filters doing what is conceptually "rows less than" or
"rows greater than" the composite page key (with null handling that
makes it more complex).

**Comment by karlcz** [comment]
This is now pending review and merge in #64 so I'm going to close this issue and leave the PR in review state.
