### ISSUE TITLE
Change valuemap to a regular table?

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#5]
For `/textfacet/` queries, should we stop using a materialized view for the valuemap and just use a regular table? In effect, the valuemap query structure could exist only transiently as part of an INSERT query rather than persisting as a view definition known to Postgresql.  This would remove the schema-level dependencies which force us to drop the view every time the catalog's model changes. With a regular table, we can continue to use a valuemap that is slighly out of sync with the catalog model.  This will also allow us to remove the logic that rebuilds a missing view at the start of a REST request, thus removing a significant source of non-deterministic request delays.

In either case the REST client needs to deal with potential inconsistencies in that a valuemap query result that may reference model elements or data elements missing on subsequent data queries.  The stronger model consistency of the materialized view provides no benefit, since the valuemap and data queries are not performed under the same transaction.

Regardless of whether we use a table or a materialized view, we still need a batch job to rebuild the valuemap and its indices periodically, since it can drift out of sync even without model changes.

**Comment by mikedarcy** [comment]
Tested and verified.
