### ISSUE TITLE
Allow cross-walking of database views

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#50]
Database views are exposed as read-only entity types in ERMrest. However, views do not have constraints and so are not cross-walkable via foreign key reference linkage to other tables or views. This makes views less useful for data consumers.

There are two possible approaches to take here:
1. Add the missing support for explicit join linkages in entity-path URLs so the client can choose the desired cross-walk without a foreign key reference link.
2. Add some annotations to express pseudo constraints for unique keys and foreign key references in views and tables, to allow cross-walking via implicit linkage.

The second approach is more convenient for data consumers but is more complex to implement and more fraught with peril. ERMrest could do good things with accurate pseudo constraint annotations, but things may go very if the DBA writes incorrect annotations. We do not want to try to do full semantic analysis to either discover or validate these pseudo constraints (something that requires understanding of the view definition, its source tables, and the constraints on those tables).

**Comment by carlkesselman** [comment]
These are not mutually exclusive, are they?

Would a possible set of correct annotations be determinable at the time a view is made based on the constraints of the columns that are included?

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Jan 4, 2016, at 11:20 AM, karlcz <notifications@github.com<mailto:notifications@github.com>> wrote:


Database views are exposed as read-only entity types in ERMrest. However, views do not have constraints and so are not cross-walkable via foreign key reference linkage to other tables or views. This makes views less useful for data consumers.

There are two possible approaches to take here:
1. Add the missing support for explicit join linkages in entity-path URLs so the client can choose the desired cross-walk without a foreign key reference link.
2. Add some annotations to express pseudo constraints for unique keys and foreign key references in views and tables, to allow cross-walking via implicit linkage.

The second approach is more convenient for data consumers but is more complex to implement and more fraught with peril. ERMrest could do good things with accurate pseudo constraint annotations, but things may go very if the DBA writes incorrect annotations. We do not want to try to do full semantic analysis to either discover or validate these pseudo constraints (something that requires understanding of the view definition, its source tables, and the constraints on those tables).

**Comment by karlcz** [comment]
Right, client-driven joins are orthogonal to server-understood references between tables. Either one may be sufficient to allow cross-walking to a view.

The problem with discovering pseudo-constraints is that you need to do more semantic analysis of the view definition's joins, grouping, aggregations, and projections. Some or all of the source table constraints MAY be applicable to the view but also MAY NOT. I don't think we want to spend time on such analysis.

Based on offline conversations, I think the consensus is to proceed with a form of non-enforced constraint overlay in ERMrest, to allow pseudo uniqueness and reference constraints to be asserted on views (and possibly regular tables) such that they appear in the model introspection even though they are not real constraints enforcing referential integrity in the database.  This would enable path-based navigation in the REST API as well as enabling any existing generic client to introspect these new links in the model.

A first cut may be the pseudo-constraint storage in our schema overlay and the logic to incorporate them into the model introspection. A second pass will be to add REST API support to manage such pseudo-constraints.

**Comment by karlcz** [comment]
This is available to play with in the view-constraints branch and PR #52 which seems to work but lacks test cases and periodic garbage collection.  It's going to be hard to test automatically with our REST test suite because the new feature only affects views, which we do not currently allow to be created by the REST API...

**Comment by karlcz** [comment]
This is merged to master now and ready for people to evaluate. Someone should play with it and then close this issue when it works for them.

**Comment by karlcz** [comment]
I believe the view support is being used in multiple catalogs at this point and there is no reason to leave this in review state.
