### ISSUE TITLE
Preliminary support for fine-grained authorization

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#51]
The upcoming 9.5 release of PostgreSQL adds row-level security where policies expressed as SQL boolean condition expression can be tested at runtime to decide whether tuples access is permitted.
- [x] Develop and test with 9.5 release candidate and/or final release of PostgreSQL.
- [x] Expose client's webauthn authentication context as PostgreSQL session variables.
- [x] Map Postgres permission denied error on RLS policy checks into HTTP Forbidden response as needed for PUT, POST, and DELETE requests.
- [x] Prototype some row-level security policies and sanity-test it.

**Comment by karlcz** [comment]
I think we're now to the point where we can start experimenting with some row-level security policies that enforce web client authentication context requirements when accessing ERMrest row content, using the latest master branch of ERMrest and a server with PostgreSQL 9.5

**Comment by carlkesselman** [comment]
Excellent.  We should probably start cutting over to this release on all our deployments.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Jan 8, 2016, at 6:02 PM, karlcz <notifications@github.com<mailto:notifications@github.com>> wrote:


I think we're now to the point where we can start experimenting with some row-level security policies that enforce web client authentication context requirements when accessing ERMrest row content, using the latest master branch of ERMrest and a server with PostgreSQL 9.5

**Comment by karlcz** [comment]
I think this generic support is done and tested. Moving to review for one of the project-specific use-cases to close it once they take it for a test drive with their own policies.

**Comment by karlcz** [comment]
@howdyjessie could you eventually concoct a test scenario with @svoinea to verify that users at the appropriate privilege levels are seeing the right forbidden errors if they try to do unauthorized things in the new RBK setup, while privileged users succeed in such a request?  That would be a good review for this issue.

**Comment by howdyjessie** [comment]
@karlcz Almost all the 403s were displayed appropriately. There was only 1 case that didn't go as expected, which was when a user attempts to delete her own image annotation but receives a 403 Forbidden instead. Not sure if that's to do with you or the RBK policies written by @svoinea.

**Comment by karlcz** [comment]
@howdyjessie 

can you send me an email with more test details:

- the server in question
- the exact ermrest entity you're trying to delete (table, row ID)
- the content of the `GET /ermrest/authn/session` resource that the client sees when authenticated

**Comment by karlcz** [comment]
Hmm, the policy as written in our provisioning recipes does not seem to match the policy as deployed in the database on rbk-dev nor rbk-staging.

I think @svoinea should review and reload all the policies to be sure they match the latest master version, then you probably need to re-test to be safe.

**Comment by karlcz** [comment]
Apologies to @svoinea it turns out postgres rewrites the policy expression so the server was current but its policy introspection output does not match the policy input we actually applied.  We have a bugfix on the annotation delete policy that may solve the bug described by @howdyjessie

**Comment by karlcz** [comment]
At any rate, I think this issue can now be closed.  The fine-grained authorization support is working.  Any further problems with a specific deployed policy should be filed as new bugs under their respective project etc.
