### ISSUE TITLE
Add create-view support to REST API

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#53]
While views can already be created manually in SQL and exposed via the automatic introspection, there is no REST API for clients to use.  This makes it difficult to test view-related features in our REST-based test suite.

While we will retain the option to create views directly in SQL, bypassing ERMrest, it may be useful to allow creation of views which will have a definition compiled from an ERMrest data path expression, i.e. the suffix of an `/entity/` `/attribute/`, or `/attributegroup/` data URL after stripping off the protocol, host, and catalog number prefix.

This should extend the current POST `schema/sname/table` API by encoding the desired `"kind": "view"` resource type and the data API path as another field in the JSON input document.

**Comment by hongsudt** [comment]
Put this issue on the wishlist wiki https://github.com/informatics-isi-edu/ermrest/wiki/Wishlist. Will close for now.
