### ISSUE TITLE
ETL script to update ermrest DB on dev to support globus_auth

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#61]
I don't think we should automatically translate existing ERMrest catalog ACLs for the new webauthn code. Rather, we should just review and set the desired ACLs using brute-force SQL commands appropriate for each deployed catalog, replacing existing ACLs with the intended ones.
On dev, we have three sample databases that have the following Globus ID users in their ACLs:
  - bugacov
  - serban
  - gpcr-data-load

and the following Globus Groups:
  - g:143f5bdc-c127-11e4-ab32-22000a1dd033
  - g:ae6f2d0a-84a5-11e3-9ff0-12313809f035

These values should be replaced with the proper globally-unique identifiers defined by the globus_auth provider.  The sample RBK data is old; while it has an `author` column in some tables, they are all NULL values and so there is no content to transform.

**Comment by karlcz** [comment]
Is this just to update the ermrest registry ACL storage along with the ERMrest changes needed?  @schuler, @serban do you know if the sample catalogs on isrd-dev have columns containing web user identifiers?

**Comment by karlcz** [comment]
Actually @hongsudt does this issue include all project catalogs?  Or are there separate issues for upgrading project-specific content that has user info stored in it? Those ETL steps will have to be performed as each server switches from old to new security. The ACLs for row-level authz will also need to be adjusted at the same time.

**Comment by hongsudt** [comment]
No.. The project-specific content will be filed as separate issues. I
already created an issue for RBK update..

**Comment by karlcz** [comment]
I think this issue description is now correct?  And it depends on the mapping table which will be provided by @ljpearlman perhaps as CSV suitable for use as a temporary table in a SQL update script.

**Comment by karlcz** [comment]
We decided not to change stored ACL formats, so there is no need for ETL on existing ermrest catalogs.

**Comment by karlcz** [comment]
This is partially addressed in informatics-isi-edu/webauthn@421e9ae190d4b1aaf95adef539b53ea3d43c4cb8 to rewrite group references in ACLs. Any individual user references are not yet converted.

**Comment by karlcz** [comment]
I think informatics-isi-edu/webauthn@703ff4ae2acd20c4658bbf867a6cf22728cf46da ermrest-acl-etl.sh script will handle the two project upgrades we care about. Can @ljpearlman and @bugacov please review.

**Comment by hongsudt** [comment]
@ljpearlman can you please review this issue?

**Comment by ljpearlman** [comment]
I think this looks good. I was poking around, and there are some group names like gpcr-data-load in ermrest ACLs; those won't work after the upgrade, but I assume they don't work now either (assigning back to Karl just in case that assumption is wrong).

**Comment by karlcz** [comment]
I think @bugacov needs to review that GPCR stuff and if necessary amend the ETL script to add other ACL entries for data loading groups.

**Comment by bugacov** [comment]
Anoop tested this script on gpcr-dev so I'll assign to him for review and to close the issue

**Comment by karlcz** [comment]
I am sure this was executed long ago and worked, so we don't need to keep open anymore.
