### ISSUE TITLE
Paging @before returning wrong set of rows 

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/ermrest#66]
@before seems to always return the first set of rows rather than the rows immediately before the before-key.

Here is an example. Replacing @before(10391) with any id always returns the first set of 10 rows.
https://dev.isrd.isi.edu/ermrest/catalog/1/entity/legacy:dataset/id::gt::100&id::lt::13000@sort(id)@before(10391)?limit=10

**Comment by karlcz** [comment]
I've pushed a fix for this to master. Please test and confirm.
