### ISSUE TITLE
PUT requests return an extra empty array

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/ermrest#69]
When sending a PUT request to edit an existing row in a table, ERMrest responds with an array with a JSON object of the updated row and then another array that's empty.

**Comment by karlcz** [comment]
I think this is fixed now in master.  It was returning one array from each of the UPDATE and INSERT SQL commands rather than splicing them together into a single result array...

**Comment by howdyjessie** [comment]
Tested on dev rbk. The response to the PUT request no longer returns an extra empty array.
