### ISSUE TITLE
Expose not-null constraint status in column introspection

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#70]
To help clients, we should include the null/not-null constraint status on columns in the introspected model resources.

**Comment by karlcz** [comment]
This is implemented now as the `nullok` boolean field of the column representation. See [column creation docs](https://github.com/informatics-isi-edu/ermrest/blob/2b49759ceac7a8b4f80906608e68a9b248e81fc7/api-doc/model/rest.md#column-creation) for representation that also applies during introspection.

**Comment by robes** [comment]
confirmed
