### ISSUE TITLE
expose etag in the response

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#71]
The client can use this tag to determine whether the model has changed.

**Comment by karlcz** [comment]
Before we modify ERMrest, it seems to me that we should just be using
the $http response.headers('etag') function to get the etag for the
response we've retrieved from ermrest.  Is there a reason this won't
work?

**Comment by karlcz** [comment]
@howdyjessie  assigning this to you to review whether you can get the http response.headers or not.  close it if we don't need to modify ermrest's actual response JSON on the server side...

**Comment by howdyjessie** [comment]
@karlcz Does ERMrest response with the etag in every response? In ermrestjs' catalog introspection function, for example, I only see `Accept` in the headers. This is what appears in the console when I print out the entire response.

<img width="639" alt="screen shot 2016-05-17 at 1 11 24 pm" src="https://cloud.githubusercontent.com/assets/4585431/15337493/efa15ddc-1c30-11e6-8bc3-dc1545fadbdd.png">

**Comment by karlcz** [comment]
Accept is a request header, not a response header...

Yes, ERMrest will have an ETag in every response that I am aware of.

**Comment by howdyjessie** [comment]
Oops, egg on my face :O I see the E-Tag here now:
<img width="716" alt="screen shot 2016-05-17 at 1 26 57 pm" src="https://cloud.githubusercontent.com/assets/4585431/15338081/30866552-1c33-11e6-8c21-e53b5dcb4f2e.png">

And yes it's accessible via `response.headers('ETag')`.

**Comment by howdyjessie** [comment]
An issue has been created in [here in ermrestjs](https://github.com/informatics-isi-edu/ermrestjs/issues/35).
