### ISSUE TITLE
Data versioning not handling truncated version table

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#73]
If an external update is done to the catalog on the server, and the _ermrest.data_version table is truncated, ermrest does not seem to be failing safely for data versioning in the ETag.  It is probably better to act like data is dirty if no data version is currently tracked for the table.  We should make sure clients refresh their caches.

Ideally, we would heal the version tracking table even on GET requests, otherwise all future requests will be cache misses until a normal data update via REST API sets the next tracked version.

**Comment by karlcz** [comment]
Commit ba35b14d529d5edae547a4fad293fdb7fbefbf71 adds self-healing for data_version during introspection.  Manually verified on existing catalog as:

1. Update service code and make some entity requests via curl
2. Using psql, truncate _ermrest.data_version and run _ermrest.model_change_event() 
3. Make some entity requests via curl

The curl response when dumping headers and searching for ETag should include a header line like: `ETag: "userinfo;*;N"` where the number _N_ should be different (larger) in step 3 than it was in step 1.

**Comment by robes** [comment]
confirmed
