### ISSUE TITLE
Change ambiguous link behavior from error to disjunctive join

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#80]
When an implicit link is requested with a path like `...table1/table2` and more than one join condition is available between the two tables, we currently raise a 409 Conflict.  Instead, we could produce a join that disjunctively applies each available link between the two tables.

This would only change an error condition into a valid query, and seems like it is unlikely to hurt usage scenarios we have thought about.

**Comment by karlcz** [comment]
Implemented in master with a basic test case in the regression test suite.  It is still possible to get a 409 Conflict if you use the more precise `.../table1/(col,...)` syntax and the column set comprises more than one foreign key reference endpoint.  A further enhancement might identify the subset of these cases where the same two tables are involved, and also use the new disjunctive join feature for these. However, some cases might actually imply different join tables and that case should remain a conflict.

**Comment by robes** [comment]
I tested this via the record app using the referenced URL from this Chaise issue:
https://github.com/informatics-isi-edu/chaise/issues/371
