### ISSUE TITLE
Close idle connections

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/ermrest#85]
Paraphrasing from @karlcz on Slack: ERMrest keeps too many idle connections to the database open when lots of catalogs are being used sporadically.

**Comment by karlcz** [comment]
I've pushed code to master that will more aggressively release idle connections when a catalog has not been used for 15 minutes or more.  It is still a bit lazy due to the way ERMrest works... it can only wake up and check for idle connections when a client request arrives, since there is no idle polling code.

With this code on dev.isrd, we should start to see that there are usually fewer stale connections if you use the following SQL query in postgres:

```
SELECT 
  datname, 
  now() - state_change AS age 
FROM pg_stat_activity
ORDER BY state_change DESC" 
```

**Comment by hongsudt** [comment]
@karlcz What's the review process on this? Randomly run the above sql statement to check the open connections?

**Comment by karlcz** [comment]
Basically, but if you are checking on a dev server with hourly update, the connections will also be closed during each httpd restart.  So, you'd have to figure out what time that happens and ignore that effect to see if the idle connections are being closed.

Also, you need to pay attention to the catalog DB names to see that they are cycling through different values.  If nobody is creating and abandoning new catalogs during that hour, you won't see much turnover in the connection pool.  There will always be at least one set of connections open to at least one catalog, unless httpd was freshly started and no client requests have been received yet.

**Comment by karlcz** [comment]
BTW I already tested this mechanism by setting a much shorter timeout period on my dev workstation, before I pushed the final code with 15 minute timeout.  I suppose we could make this a configuration parameter but it seems insignificant to me.

**Comment by howdyjessie** [comment]
If I tested this correctly then this I can confirm this fixes the issue. A few minutes after an hourly update on dev isrd, I tracked a catalog's age until it reached a little over 15 minutes old. Then I loaded a Chaise app to make a client request, and the catalog's age is now a blank value.

**Comment by hongsudt** [comment]
I am closing this issue since Jessie has verified the behavior.
