### ISSUE TITLE
expose fkref constraint names

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#86]
For introspection and management. Could be useful for referencing fkref in future annotation.

**Comment by karlcz** [comment]
This is implemented in master and documented in https://github.com/informatics-isi-edu/ermrest/blob/master/api-doc/model/rest.md#foreign-key-creation 

In short, the foreign key reference JSON object now has a `names` field that exposes the constraint names. We used a compact notation `[S, C]` for the _schema name_ and _constraint name_ under the assumption we'd use these in annotations and want to keep it concise and easy to type without any weird encoding rules to worry about.

**Comment by robes** [comment]
@karlcz _Should_ we support multiple names on a FK? Is this an esoteric feature of SQL standards that we should say "don't do that" to our users...? This seems to introduce complications downstream. I.e., the ermrestjs model will need to be `ForeignKeyRef.constrain_names -> array of name pairs` (plural). The check against the 'visible-foreignkeys' annotation will have to check these arrays. Etc. Not a huge deal but is this a feature that is really needed to justify the additional effort?

**Comment by karlcz** [comment]
There's no good way to protect against encountering this other than using the full mapping structure to identify constraints. So, I am against trying to hide the detail in ERMrest's actual model representation.

These are essentially just aliases for a logical constraint as far as a model consumer is concerned. You can just merge them down into one lookup mapping tree like: `fkrs[schema_name][constraint_name]` or similar, where the same FKR can be mapped from several names.  I would think you'd want to make that mapping table anyway, so the only extra effort is looping over the names while registering each new FKR into the table.
