### ISSUE TITLE
create markdown type

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#87]
We need that to test the display functionality.

**Comment by karlcz** [comment]
ermrest/master now defines a `markdown` domain type along with `longtext` for newly created catalogs. It also adds this to the default ermrest_config.json on new deployments.  The test suite now uses those for test column definitions too.

Existing deployments will still need to add such domains to their existing ermrest_config.json, and define such domains in SQL for their existing catalog DBs. There is still no REST API to define new domains on the fly.
