### ISSUE TITLE
document practices for using sql view with row-level security

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#89]
I already have a wikii (deployment pittfall) under the division repo wiki. Can you please add some more detail related to row-level security or add a link on that wiki if you think the content should be somewhere else?

**Comment by karlcz** [comment]
Issue moved to [informatics-isi-edu/division #91](https://github.com/informatics-isi-edu/division/issues/91) via [**ZenHub**](https://www.zenhub.com/)
