### ISSUE TITLE
attributegroup raises an internal server error when a schema name is present in the group key.

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/ermrest#9]
The tested query:

curl -k -X GET -H 'Accept: application/json' "https://dev.facebase.org/ermrest/catalog/1/attributegroup/Microscopy:Experiment/ID=20131112-myantibody1-SV-0/B:=Microscopy:Slide/Microscopy:Experiment:*;BB:=array(B:*)"

The stack trace:

[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164] Traceback (most recent call last):
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/web.py-0.37-py2.6.egg/web/application.py", line 239, in process
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]     return self.handle()
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/web.py-0.37-py2.6.egg/web/application.py", line 230, in handle
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]     return self._delegate(fn, self.fvars, args)
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/web.py-0.37-py2.6.egg/web/application.py", line 405, in _delegate
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]     return handle_class(f)
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/web.py-0.37-py2.6.egg/web/application.py", line 396, in handle_class
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]     return tocall(*args)
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/ermrest/ermrest_apis.py", line 283, in GET
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]     return self.METHOD('GET')
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/ermrest/ermrest_apis.py", line 250, in METHOD
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]     first = result.next()
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/ermrest/sanepg2.py", line 146, in pooled_perform
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]     result = bodyfunc(conn, cur)
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/ermrest/url/ast/data/path.py", line 191, in wrapbody
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]     return body(conn, cur)
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/ermrest/url/ast/data/__init__.py", line 321, in body
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]     agpath = self.resolve(model)
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/ermrest/url/ast/data/__init__.py", line 309, in resolve
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]     return ermpath.AttributeGroupPath(epath, self.groupkeys, self.attributes)
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/ermrest/ermpath.py", line 1413, in __init__
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]     self.groupkeys = self._preprocess_attributes(groupkeys)
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/ermrest/ermpath.py", line 827, in _preprocess_attributes
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]     col, base = attribute.resolve_column(self.epath._model, self.epath)
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]   File "/usr/lib/python2.6/site-packages/ermrest/ermpath.py", line 142, in resolve_column
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164]     return (model.lookup_table(n0, n1).columns[n2], None)
[Thu Jul 16 09:01:54 2015] [error] [client 128.9.128.164] KeyError: '*'

**Comment by karlcz** [comment]
The internal error is fixed in 2705ee3632e12c196f6a4c57dedee9931fcb94c4 and the nature of the error messages are further improved in 9b071b46112b64b5fef3f13e6dd28c7b6fc8c48f.
