### ISSUE TITLE
Slightly misleading error message when a table in  model_table_annotation doesn't exist

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrest#92]
If model_table_annotation has an entry for a table that doesn't exist (or isn't accessible), the error thrown is "Table X does not exist in schema Y", where X is the table specified in the request, even if it's not the problem table. That table name is a red herring in the case where the requested table is fine and the problem is an entry for some other table. A more generic message (with the schema name but without the table name) would be less confusing.

**Comment by karlcz** [comment]
You mean that the annotation storage table has invalid/dangling annotations and it throws this error during introspection of the model at the beginning of servicing requests?

**Comment by karlcz** [comment]
I am unable to reproduce this.  I manually added table-annotation entries with mismatched schema and/or table names, ran _ermrest.model_change_event(), restarted httpd, and accessed schema and data APIs for valid tables and everything worked normally, ignoring the broken annotations.
