### ISSUE TITLE
Linking column resolution for composites deviates from documentation

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#94]
The documentation says a composite link endpoint can be specified as `(S:T:C1,C2,...)` but it instead seems to resolve `C2` against the datapath first and then complains that the columns do not belong to the same table.

**Comment by karlcz** [comment]
@RFSH a fix for this is now in ermrest/master... maybe you can review the API behavior since you detected the problem?

**Comment by RFSH** [comment]
@karlcz It is working as expected now.
Thanks.

**Comment by hongsudt** [comment]
@karlcz  I am closing the issue then.
