### ISSUE TITLE
Support outer joins

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#99]
The current entity-path syntax is implicitly defining inner joins.  For some common use cases, any of the outer join variants (left, right, full) would be very useful.

This should be defined as a syntax extension that is backwards compatible with the current syntax, i.e. the default remains inner join and the optional syntax would be things that were previously invalid ermrest URLs.

**Comment by karlcz** [comment]
This is implemented in 7a24460852f5d5d6f9a1683f5636a810be95f358 as optional `left`, `right`, and `full` prefixes to the existing explicit column mapping notation `(left cols...)=(right cols...)` to select left outer, right outer, and full outer joins, respectively.  This commit adds the feature, docs, and tests.

Perhaps @robes and/or @RFSH could tinker with it to sanity check the behavior, but I'm pretty sure it is working correctly...

**Comment by RFSH** [comment]
@karlcz I manually tested this api call on several datasets and it's working as expected. I can test it thoroughly in ermrestjs when I implemented the linked data.
